"""Public facade for the brokerai CLI package."""

from __future__ import annotations

from t212ai.app.config import DEFAULT_ENV_FILE_NAME, get_app_settings
from t212ai.app.runtime import build_runtime

from .common import (
    _bool_to_env,
    _configure_app_logging,
    _display_env_value,
    _env_truthy,
    _mask_secret,
    _safe_choice,
    load_settings_from_cli,
    parse_duration_to_seconds,
)
from .config_metadata import (
    ConfigKey,
    all_config_keys,
    command_config_explain,
    command_config_list,
    command_config_sample,
    command_config_validate,
    find_config_key,
)
from .constants import (
    OPENAI_DEFAULT_MODEL_OPTIONS,
    OPENAI_REASONING_MODEL_OPTIONS,
    OPENAI_SMART_MODEL_OPTIONS,
)
from .config_wizard import (
    _active_broker_credential_keys,
    _clear_env_keys,
    _drop_new_empty_inactive_broker_credentials,
    _format_env_assignment,
    _format_env_value,
    _prompt_alpaca_credentials,
    _prompt_iana_timezone,
    _prompt_model_context_limit,
    _prompt_openai_model,
    _prompt_required,
    _prompt_trading212_credentials,
    _section_has_existing_values,
    _should_update_section,
    _write_step_intro,
    apply_configuration_wizard,
    build_managed_env_values,
    command_configure,
    update_env_file,
)
from .doctor import command_doctor
from .io import TerminalIO
from .parser import build_parser, main
from .reports import (
    render_configuration_review,
    render_doctor_report,
    render_provider_smoke_report,
    render_reconcile_failure,
    render_run_bot_failure,
    render_scheduler_failure,
    render_scheduler_maintenance_result,
    render_scheduler_process_detail,
    render_scheduler_process_list,
    render_scheduler_status,
)
from .run import (
    command_run_alpaca_news_stream,
    command_run_bot,
    command_run_reconcile_once,
    command_run_scheduler_once,
    command_run_scheduler_worker,
    command_run_worker,
    run_reconcile_once,
    run_reconcile_worker,
    run_scheduler_once,
    run_scheduler_worker,
)
from .scheduler import (
    _build_scheduler_runtime_for_command,
    _cutoff_from_duration_or_iso,
    command_scheduler_cleanup,
    command_scheduler_export,
    command_scheduler_list,
    command_scheduler_recover_stale,
    command_scheduler_show,
    command_scheduler_status,
)

__all__ = [
    "ConfigKey",
    "DEFAULT_ENV_FILE_NAME",
    "OPENAI_DEFAULT_MODEL_OPTIONS",
    "OPENAI_REASONING_MODEL_OPTIONS",
    "OPENAI_SMART_MODEL_OPTIONS",
    "TerminalIO",
    "_active_broker_credential_keys",
    "_bool_to_env",
    "_build_scheduler_runtime_for_command",
    "_clear_env_keys",
    "_configure_app_logging",
    "_cutoff_from_duration_or_iso",
    "_display_env_value",
    "_drop_new_empty_inactive_broker_credentials",
    "_env_truthy",
    "_format_env_assignment",
    "_format_env_value",
    "_mask_secret",
    "_prompt_alpaca_credentials",
    "_prompt_iana_timezone",
    "_prompt_model_context_limit",
    "_prompt_openai_model",
    "_prompt_required",
    "_prompt_trading212_credentials",
    "_safe_choice",
    "_section_has_existing_values",
    "_should_update_section",
    "_write_step_intro",
    "all_config_keys",
    "apply_configuration_wizard",
    "build_managed_env_values",
    "build_parser",
    "build_runtime",
    "command_config_explain",
    "command_config_list",
    "command_config_sample",
    "command_config_validate",
    "command_configure",
    "command_doctor",
    "command_run_alpaca_news_stream",
    "command_run_bot",
    "command_run_reconcile_once",
    "command_run_scheduler_once",
    "command_run_scheduler_worker",
    "command_run_worker",
    "command_scheduler_cleanup",
    "command_scheduler_export",
    "command_scheduler_list",
    "command_scheduler_recover_stale",
    "command_scheduler_show",
    "command_scheduler_status",
    "find_config_key",
    "get_app_settings",
    "load_settings_from_cli",
    "main",
    "parse_duration_to_seconds",
    "render_configuration_review",
    "render_doctor_report",
    "render_provider_smoke_report",
    "render_reconcile_failure",
    "render_run_bot_failure",
    "render_scheduler_failure",
    "render_scheduler_maintenance_result",
    "render_scheduler_process_detail",
    "render_scheduler_process_list",
    "render_scheduler_status",
    "run_reconcile_once",
    "run_reconcile_worker",
    "run_scheduler_once",
    "run_scheduler_worker",
    "update_env_file",
]
