"""Reusable GenAI tool definitions and mappings."""

from .scrape_article import SCRAPE_ARTICLE_TOOL, scrape_article
from .search_registry import SearchResultRegistry
from .searxng import SEARXNG_SEARCH_TOOL, searxng_search
from .tools import (
    CHAT_TOOLBOX,
    MARKET_DATA_TOOLBOX,
    RESEARCH_TOOLBOX,
    TOOLBOXES,
    ToolBox,
    YAHOO_MARKET_CONTEXT_TOOLBOX,
    build_tool_mapping,
    build_tool_mapping_for,
)
from .yahoo_finance import (
    YAHOO_ANALYST_SNAPSHOT_TOOL,
    YAHOO_MARKET_SNAPSHOT_TOOL,
    YAHOO_OPTIONS_SNAPSHOT_TOOL,
    YAHOO_PRICE_HISTORY_TOOL,
    YAHOO_PRICE_SUMMARY_TOOL,
    YAHOO_PRICE_SUMMARY_WITH_CHART_REFS_TOOL,
    YAHOO_QUOTE_SNAPSHOT_TOOL,
    YAHOO_SYMBOL_SEARCH_TOOL,
    YAHOO_VOLUME_MONITOR_TOOL,
    yahoo_analyst_snapshot,
    yahoo_market_snapshot,
    yahoo_options_snapshot,
    yahoo_price_history,
    yahoo_price_summary,
    yahoo_price_summary_with_chart_refs,
    yahoo_quote_snapshot,
    yahoo_symbol_search,
    yahoo_volume_monitor,
)

__all__ = [
    "ToolBox",
    "SearchResultRegistry",
    "CHAT_TOOLBOX",
    "RESEARCH_TOOLBOX",
    "MARKET_DATA_TOOLBOX",
    "YAHOO_MARKET_CONTEXT_TOOLBOX",
    "TOOLBOXES",
    "build_tool_mapping",
    "build_tool_mapping_for",
    "SEARXNG_SEARCH_TOOL",
    "searxng_search",
    "SCRAPE_ARTICLE_TOOL",
    "scrape_article",
    "YAHOO_PRICE_HISTORY_TOOL",
    "YAHOO_PRICE_SUMMARY_TOOL",
    "YAHOO_PRICE_SUMMARY_WITH_CHART_REFS_TOOL",
    "YAHOO_SYMBOL_SEARCH_TOOL",
    "YAHOO_QUOTE_SNAPSHOT_TOOL",
    "YAHOO_MARKET_SNAPSHOT_TOOL",
    "YAHOO_VOLUME_MONITOR_TOOL",
    "YAHOO_OPTIONS_SNAPSHOT_TOOL",
    "YAHOO_ANALYST_SNAPSHOT_TOOL",
    "yahoo_price_history",
    "yahoo_price_summary",
    "yahoo_price_summary_with_chart_refs",
    "yahoo_symbol_search",
    "yahoo_quote_snapshot",
    "yahoo_market_snapshot",
    "yahoo_volume_monitor",
    "yahoo_options_snapshot",
    "yahoo_analyst_snapshot",
]
