from __future__ import annotations

from pathlib import Path

from t212ai.agent.intents import AgentIntent, IntentKind
from t212ai.agent.planner import AgentPlan
from t212ai.app.config import get_app_settings
from t212ai.app.runtime import build_runtime
from t212ai.telegram.bridge import build_agent_message_handler_if_configured
from t212ai.telegram.models import TelegramInboundMessage, TelegramOutboundMessage


class FakeRuntimeGenAIClient:
    def __init__(self, settings) -> None:
        self.settings = settings

    def chat_model_for(self, purpose: str | None = None) -> str:
        return f"{purpose or 'default'}-model"

    def generate_structured(
        self,
        schema: type,
        system_prompt: str,
        chat_message: object,
        *,
        model: str | None = None,
        temperature: float = 0.2,
        max_tokens: int | None = None,
    ) -> object:
        del schema, system_prompt, chat_message, model, temperature, max_tokens
        return AgentPlan(
            intent=AgentIntent(kind=IntentKind.UNKNOWN),
            summary="Plan generated by runtime fake client.",
            required_context=["context"],
            assumptions=["assumption"],
            risks=["risk"],
        )


class FakeTrading212Client:
    @classmethod
    def from_settings(cls, settings=None):
        del settings
        return cls()

    def get_account_summary(self):
        raise NotImplementedError

    def list_positions(self):
        raise NotImplementedError

    def list_pending_orders(self):
        raise NotImplementedError

    def get_order(self, order_id: int):
        raise NotImplementedError

    def place_market_order(self, request):
        raise NotImplementedError

    def place_limit_order(self, request):
        raise NotImplementedError

    def place_stop_order(self, request):
        raise NotImplementedError

    def place_stop_limit_order(self, request):
        raise NotImplementedError

    def cancel_order(self, order_id: int):
        raise NotImplementedError


class FakeAlphaVantageClient:
    @classmethod
    def from_settings(cls, settings=None):
        del settings
        return cls()


class FakeRedditClient:
    @classmethod
    def from_settings(cls, settings=None):
        del settings
        return cls()


def test_build_runtime_records_genai_error_when_llm_is_missing(tmp_path: Path) -> None:
    settings = get_app_settings(
        env={
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )

    runtime = build_runtime(settings)

    assert runtime.guideline_memory_service.render_markdown() == ""
    assert runtime.history_manager is not None
    assert runtime.genai_client is None
    assert runtime.main_orchestrator is None
    assert "genai_client" in runtime.component_errors
    assert not runtime.has_agent_runtime


def test_build_runtime_wires_agent_stack_when_llm_is_configured(
    monkeypatch,
    tmp_path: Path,
) -> None:
    import t212ai.app.runtime as runtime_module

    monkeypatch.setattr(runtime_module, "GenAIClient", FakeRuntimeGenAIClient)
    settings = get_app_settings(
        env={
            "LLM_PROVIDER": "openai",
            "OPENAI_API_KEY": "openai-key",
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )

    runtime = build_runtime(settings)

    assert runtime.genai_client is not None
    assert runtime.agent_reasoner is not None
    assert runtime.agent_judge is not None
    assert runtime.main_orchestrator is not None
    assert runtime.has_agent_runtime
    assert runtime.component_errors == {}


def test_build_runtime_builds_optional_provider_stacks(
    monkeypatch,
    tmp_path: Path,
) -> None:
    import t212ai.app.runtime as runtime_module

    monkeypatch.setattr(runtime_module, "GenAIClient", FakeRuntimeGenAIClient)
    monkeypatch.setattr(runtime_module, "Trading212Client", FakeTrading212Client)
    monkeypatch.setattr(runtime_module, "AlphaVantageClient", FakeAlphaVantageClient)
    monkeypatch.setattr(runtime_module, "RedditClient", FakeRedditClient)
    settings = get_app_settings(
        env={
            "LLM_PROVIDER": "openai",
            "OPENAI_API_KEY": "openai-key",
            "BROKER_PROVIDER": "trading212",
            "T212_API_KEY": "t212-key",
            "T212_API_SECRET": "t212-secret",
            "YAHOO_ENABLED": "true",
            "ALPHA_VANTAGE_ENABLED": "true",
            "ALPHA_VANTAGE_API_KEY": "alpha-key",
            "REDDIT_ENABLED": "true",
            "REDDIT_CLIENT_ID": "reddit-id",
            "REDDIT_CLIENT_SECRET": "reddit-secret",
            "REDDIT_REFRESH_TOKEN": "refresh-token",
            "REDDIT_USER_AGENT": "server:t212ai:test (by /u/tester)",
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )

    runtime = build_runtime(settings)

    assert runtime.trading212_client is not None
    assert runtime.trading212_service is not None
    assert runtime.yahoo_client is not None
    assert runtime.alpha_vantage_client is not None
    assert runtime.reddit_client is not None
    assert runtime.reddit_service is not None
    assert runtime.has_broker_runtime
    assert runtime.has_market_data_runtime


def test_runtime_backed_agent_handler_reuses_runtime_history(
    monkeypatch,
    tmp_path: Path,
) -> None:
    import t212ai.app.runtime as runtime_module

    monkeypatch.setattr(runtime_module, "GenAIClient", FakeRuntimeGenAIClient)
    settings = get_app_settings(
        env={
            "LLM_PROVIDER": "openai",
            "OPENAI_API_KEY": "openai-key",
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )
    runtime = build_runtime(settings)

    handler = build_agent_message_handler_if_configured(runtime=runtime)
    response = handler(
        TelegramInboundMessage(
            chat_id=123,
            text="show my portfolio",
            message_id=1,
        )
    )
    history = runtime.history_manager.get_context_window(123)

    assert isinstance(response, TelegramOutboundMessage)
    assert "portfolio_analyst prepared a plan" in response.text
    assert history.retained_count == 2
    assert [message.role for message in history.messages] == ["user", "assistant"]
