from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path
from decimal import Decimal

from t212ai.agent.intents import AgentIntent, IntentKind
from t212ai.agent.planner import AgentPlan
from t212ai.capabilities import (
    BrokerExecutionService,
    BrokerReadService,
    CommunityResearchService,
    DisclosureService,
    MarketDataService,
    MarketIntelligenceService,
)
from t212ai.app.config import get_app_settings
from t212ai.app.runtime import build_runtime
from t212ai.brokers.trading212.models import (
    AccountSummary,
    Cash,
    Investments,
    PaginatedResponseHistoricalOrder,
    Order,
    OrderSide,
    OrderStatus,
    OrderType,
    PortfolioSnapshot,
    TimeValidity,
)
from t212ai.telegram.bridge import build_agent_message_handler_if_configured
from t212ai.telegram.models import TelegramInboundMessage, TelegramOutboundMessage


class FakeRuntimeGenAIClient:
    def __init__(self, settings) -> None:
        self.settings = settings

    def chat_model_for(self, purpose: str | None = None) -> str:
        return f"{purpose or 'default'}-model"

    def generate_structured(
        self,
        schema: type,
        system_prompt: str,
        chat_message: object,
        *,
        model: str | None = None,
        temperature: float = 0.2,
        max_tokens: int | None = None,
    ) -> object:
        del schema, system_prompt, chat_message, model, temperature, max_tokens
        return AgentPlan(
            intent=AgentIntent(kind=IntentKind.UNKNOWN),
            summary="Plan generated by runtime fake client.",
            required_context=["context"],
            assumptions=["assumption"],
            risks=["risk"],
        )


class FakeTrading212Client:
    reviewed_at = datetime(2026, 4, 27, 12, 0, tzinfo=timezone.utc)

    @classmethod
    def from_settings(cls, settings=None):
        del settings
        return cls()

    def get_account_summary(self):
        return AccountSummary(
            id=1,
            currency="EUR",
            cash=Cash(
                available_to_trade=Decimal("1000"),
                reserved_for_orders=Decimal("200"),
            ),
            investments=Investments(
                current_value=Decimal("2500"),
                total_cost=Decimal("2200"),
                unrealized_profit_loss=Decimal("300"),
            ),
            total_value=Decimal("3500"),
        )

    def list_positions(self):
        return []

    def list_pending_orders(self):
        return [
            Order(
                id=22,
                ticker="MSFT_US_EQ",
                currency="EUR",
                quantity=Decimal("1"),
                side=OrderSide.BUY,
                status=OrderStatus.NEW,
                type=OrderType.LIMIT,
                limit_price=Decimal("320"),
                time_in_force=TimeValidity.DAY,
                created_at=self.reviewed_at - timedelta(hours=2),
            )
        ]

    def get_order(self, order_id: int):
        raise NotImplementedError

    def list_historical_orders(self, *, cursor=None, ticker=None, limit=None):
        del cursor, ticker, limit
        return PaginatedResponseHistoricalOrder(items=[])

    def place_market_order(self, request):
        raise NotImplementedError

    def place_limit_order(self, request):
        raise NotImplementedError

    def place_stop_order(self, request):
        raise NotImplementedError

    def place_stop_limit_order(self, request):
        raise NotImplementedError

    def cancel_order(self, order_id: int):
        raise NotImplementedError


class FakeAlphaVantageClient:
    @classmethod
    def from_settings(cls, settings=None):
        del settings
        return cls()


class FakeRedditClient:
    @classmethod
    def from_settings(cls, settings=None):
        del settings
        return cls()


def test_build_runtime_records_genai_error_when_llm_is_missing(tmp_path: Path) -> None:
    settings = get_app_settings(
        env={
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )

    runtime = build_runtime(settings)

    assert runtime.guideline_memory_service.render_markdown() == ""
    assert runtime.history_manager is not None
    assert runtime.db_engine is not None
    assert runtime.db_session_factory is not None
    assert runtime.pending_action_service is not None
    assert runtime.proposal_service is not None
    assert runtime.calculator_service is not None
    assert runtime.market_data_service is not None
    assert isinstance(runtime.market_data_service, MarketDataService)
    assert runtime.market_intelligence_service is None
    assert runtime.community_research_service is None
    assert runtime.disclosure_service is not None
    assert isinstance(runtime.disclosure_service, DisclosureService)
    assert runtime.search_service is None
    assert runtime.broker_read_service is None
    assert runtime.broker_execution_service is None
    assert runtime.capability_registry["market_data"].selected_provider == "yahoo"
    assert runtime.capability_registry["market_data"].ready
    assert runtime.capability_registry["disclosure"].selected_provider == "sec_edgar"
    assert runtime.capability_registry["disclosure"].ready
    assert runtime.capability_registry["broker_read"].implementation is None
    assert runtime.specialist_tooling is not None
    assert runtime.specialist_tooling.order_toolbox is None
    assert set(runtime.toolboxes["market_analyst"].tools_by_name) == {
        "market_get_market_snapshot",
        "market_get_volume_monitor",
        "edgar_recent_ownership_activity",
        "edgar_recent_major_stake_activity",
        "edgar_company_disclosure_snapshot",
    }
    assert runtime.sec_edgar_client is not None
    assert runtime.insider_manager is not None
    assert runtime.genai_client is None
    assert runtime.calculator_agent is None
    assert runtime.main_orchestrator is None
    assert "genai_client" in runtime.component_errors
    assert not runtime.has_agent_runtime


def test_build_runtime_wires_agent_stack_when_llm_is_configured(
    monkeypatch,
    tmp_path: Path,
) -> None:
    import t212ai.app.runtime as runtime_module

    monkeypatch.setattr(runtime_module, "GenAIClient", FakeRuntimeGenAIClient)
    settings = get_app_settings(
        env={
            "LLM_PROVIDER": "openai",
            "OPENAI_API_KEY": "openai-key",
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )

    runtime = build_runtime(settings)

    assert runtime.genai_client is not None
    assert runtime.agent_reasoner is not None
    assert runtime.agent_judge is not None
    assert runtime.main_orchestrator is not None
    assert runtime.db_engine is not None
    assert runtime.db_session_factory is not None
    assert runtime.pending_action_service is not None
    assert runtime.proposal_service is not None
    assert runtime.calculator_service is not None
    assert runtime.calculator_agent is not None
    assert runtime.market_data_service is not None
    assert runtime.disclosure_service is not None
    assert runtime.sec_edgar_client is not None
    assert runtime.insider_manager is not None
    assert runtime.has_agent_runtime
    assert runtime.component_errors == {}


def test_build_runtime_builds_optional_provider_stacks(
    monkeypatch,
    tmp_path: Path,
) -> None:
    import t212ai.app.runtime as runtime_module

    monkeypatch.setattr(runtime_module, "GenAIClient", FakeRuntimeGenAIClient)
    monkeypatch.setattr(runtime_module, "Trading212Client", FakeTrading212Client)
    monkeypatch.setattr(runtime_module, "AlphaVantageClient", FakeAlphaVantageClient)
    monkeypatch.setattr(runtime_module, "RedditClient", FakeRedditClient)
    settings = get_app_settings(
        env={
            "LLM_PROVIDER": "openai",
            "OPENAI_API_KEY": "openai-key",
            "BROKER_PROVIDER": "trading212",
            "T212_API_KEY": "t212-key",
            "T212_API_SECRET": "t212-secret",
            "YAHOO_ENABLED": "true",
            "ALPHA_VANTAGE_ENABLED": "true",
            "ALPHA_VANTAGE_API_KEY": "alpha-key",
            "REDDIT_ENABLED": "true",
            "REDDIT_CLIENT_ID": "reddit-id",
            "REDDIT_CLIENT_SECRET": "reddit-secret",
            "REDDIT_REFRESH_TOKEN": "refresh-token",
            "REDDIT_USER_AGENT": "server:t212ai:test (by /u/tester)",
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )

    runtime = build_runtime(settings)

    assert runtime.trading212_client is not None
    assert runtime.trading212_service is not None
    assert runtime.broker_read_service is not None
    assert runtime.broker_execution_service is not None
    assert isinstance(runtime.broker_read_service, BrokerReadService)
    assert isinstance(runtime.broker_execution_service, BrokerExecutionService)
    assert runtime.pending_action_service is not None
    assert runtime.proposal_service is not None
    assert runtime.reconciliation_service is not None
    assert runtime.portfolio_summary_workflow is not None
    assert runtime.pending_orders_review_workflow is not None
    assert runtime.yahoo_client is not None
    assert runtime.market_data_service is not None
    assert isinstance(runtime.market_data_service, MarketDataService)
    assert runtime.alpha_vantage_client is not None
    assert runtime.market_intelligence_service is not None
    assert isinstance(runtime.market_intelligence_service, MarketIntelligenceService)
    assert runtime.reddit_client is not None
    assert runtime.reddit_service is not None
    assert runtime.community_research_service is not None
    assert isinstance(runtime.community_research_service, CommunityResearchService)
    assert runtime.sec_edgar_client is not None
    assert runtime.insider_manager is not None
    assert runtime.disclosure_service is not None
    assert isinstance(runtime.disclosure_service, DisclosureService)
    assert runtime.capability_registry["broker_read"].ready
    assert runtime.capability_registry["broker_execution"].ready
    assert runtime.capability_registry["market_intelligence"].ready
    assert runtime.capability_registry["community_research"].ready
    assert not runtime.capability_registry["search"].ready
    market_tools = runtime.toolboxes["market_analyst"].tools_by_name
    assert "alpha_vantage_most_actively_traded" in market_tools
    assert "searxng_search" not in market_tools
    assert runtime.specialist_tooling is not None
    assert runtime.specialist_tooling.order_toolbox is not None
    assert runtime.has_broker_runtime
    assert runtime.has_market_data_runtime


def test_runtime_backed_agent_handler_reuses_runtime_history(
    monkeypatch,
    tmp_path: Path,
) -> None:
    import t212ai.app.runtime as runtime_module

    monkeypatch.setattr(runtime_module, "GenAIClient", FakeRuntimeGenAIClient)
    settings = get_app_settings(
        env={
            "LLM_PROVIDER": "openai",
            "OPENAI_API_KEY": "openai-key",
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )
    runtime = build_runtime(settings)

    handler = build_agent_message_handler_if_configured(runtime=runtime)
    response = handler(
        TelegramInboundMessage(
            chat_id=123,
            text="show my portfolio",
            message_id=1,
        )
    )
    history = runtime.history_manager.get_context_window(123)

    assert isinstance(response, TelegramOutboundMessage)
    assert "portfolio_analyst prepared a plan" in response.text
    assert history.retained_count == 2
    assert [message.role for message in history.messages] == ["user", "assistant"]


def test_runtime_backed_agent_handler_uses_portfolio_workflow_when_broker_is_configured(
    monkeypatch,
    tmp_path: Path,
) -> None:
    import t212ai.app.runtime as runtime_module

    monkeypatch.setattr(runtime_module, "GenAIClient", FakeRuntimeGenAIClient)
    monkeypatch.setattr(runtime_module, "Trading212Client", FakeTrading212Client)
    settings = get_app_settings(
        env={
            "LLM_PROVIDER": "openai",
            "OPENAI_API_KEY": "openai-key",
            "BROKER_PROVIDER": "trading212",
            "T212_API_KEY": "t212-key",
            "T212_API_SECRET": "t212-secret",
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )
    runtime = build_runtime(settings)

    handler = build_agent_message_handler_if_configured(runtime=runtime)
    response = handler(
        TelegramInboundMessage(
            chat_id=123,
            text="show my portfolio",
            message_id=1,
        )
    )

    assert isinstance(response, TelegramOutboundMessage)
    assert "Trading 212 portfolio summary." in response.text
