from __future__ import annotations

from datetime import datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path
import re
from types import SimpleNamespace

from t212ai.agent import (
    AgentJudge,
    AgentInvocationContext,
    AgentReasoningContext,
    AgentReasoner,
    AgentRequest,
    ChatHistoryManager,
    ChatHistoryMessage,
    ChatHistoryPolicy,
    ConfigurablePlannerAgent,
    ConfigurableReasonerAgent,
    GroupedAgentPlan,
    GroupedPlanExecutionResult,
    GroupedPlanExecutor,
    InMemoryChatHistoryStore,
    MainOrchestratorAgent,
    PlanAction,
    PlanActionExecution,
    PlanActionGroup,
    PlanActionGroupExecution,
    PlanExecutionMode,
    PortfolioAnalystAgent,
    SchedulerAgent,
    TaskComplexity,
    build_specialist_agents,
    classify_message,
)
from t212ai.agent.history import ChatHistoryWindow
from t212ai.agent.intents import AgentIntent, IntentKind
from t212ai.agent.planner import StructuredAgentPlan
from t212ai.agent.schemas import (
    AgentCritique,
)
from t212ai.app.bootstrap import assess_settings
from t212ai.app.config import get_app_settings
from t212ai.brokers.tools import build_broker_order_action_toolbox
from t212ai.brokers.trading212.models import (
    AccountSummary,
    Cash,
    Investments,
    Order,
    OrderSide,
    OrderStatus,
    OrderType,
    PortfolioSnapshot,
    TimeValidity,
)
from t212ai.telegram.bridge import (
    build_agent_message_handler_if_configured,
    build_default_message_handler,
)
from t212ai.telegram.models import TelegramInboundMessage, TelegramOutboundMessage
from t212ai.persistence.database import build_engine, build_session_factory, ensure_schema
from t212ai.scheduler import ScheduledProcessService
from t212ai.workflows import PendingOrdersReviewWorkflow, PortfolioSummaryWorkflow


class FakeGenAIClient:
    def __init__(self) -> None:
        self.calls: list[dict[str, object]] = []
        self.model_purposes: list[str] = []

    def chat_model_for(self, purpose: str | None = None) -> str:
        resolved = purpose or "default"
        self.model_purposes.append(resolved)
        return f"{resolved}-model"

    def generate_structured(
        self,
        schema: type,
        system_prompt: str,
        chat_message: object,
        *,
        model: str | None = None,
        temperature: float = 0.2,
        max_tokens: int | None = None,
        ) -> object:
        self.calls.append(
            {
                "schema": schema.__name__,
                "system_prompt": system_prompt,
                "chat_message": chat_message,
                "model": model,
                "temperature": temperature,
                "max_tokens": max_tokens,
            }
        )
        if schema is AgentCritique:
            return AgentCritique(
                passed=True,
                summary="Looks complete.",
                confidence=0.9,
            )
        if schema is AgentReasoningContext:
            return AgentReasoningContext(
                task_interpretation="Interpret the current request.",
                known_facts=["The user asked for market context."],
                assumptions=["Use available configured capabilities."],
                ambiguities=[],
                required_evidence=["market snapshot"],
                safety_constraints=["Do not execute broker actions."],
                relevant_capabilities=["market data"],
                approval_notes=[],
                can_proceed=True,
                confidence=0.8,
            )
        if schema is GroupedAgentPlan:
            return GroupedAgentPlan(
                intent={
                    "kind": IntentKind.UNKNOWN,
                    "entities": [],
                    "confidence": 0.0,
                },
                summary="Grouped plan generated by fake GenAI.",
                required_context=["market data"],
                action_groups=[
                    {
                        "group_id": "group_1",
                        "title": "Fetch independent context",
                        "execution_mode": "parallel",
                        "actions": [
                            {
                                "action_id": "action_1",
                                "tool_name": "market_get_market_snapshot",
                                "purpose": "Fetch market snapshot.",
                                "input_summary": "Broad market context.",
                                "expected_output": "Market snapshot payload.",
                                "output_key": "market_snapshot",
                                "risk_class": "read_only",
                            },
                            {
                                "action_id": "action_2",
                                "tool_name": "edgar_company_disclosure_snapshot",
                                "purpose": "Fetch disclosure context.",
                                "input_summary": "Official disclosures.",
                                "expected_output": "Disclosure payload.",
                                "output_key": "disclosures",
                                "risk_class": "read_only",
                            },
                        ],
                    },
                    {
                        "group_id": "group_2",
                        "title": "Synthesize answer",
                        "execution_mode": "sequential",
                        "actions": [
                            {
                                "action_id": "action_3",
                                "purpose": "Synthesize user answer.",
                                "input_summary": "Use gathered context.",
                                "expected_output": "Concise final answer.",
                                "depends_on": ["action_1", "action_2"],
                                "output_key": "final_summary",
                                "risk_class": "read_only",
                            }
                        ],
                    },
                ],
                assumptions=["Use available configured capabilities."],
                expected_final_output="Concise market context summary.",
                task_complexity=TaskComplexity.COMPLEX,
            )
        return StructuredAgentPlan(
            intent={"kind": IntentKind.UNKNOWN, "entities": [], "confidence": 0.0},
            summary="Plan generated by fake GenAI.",
            required_context=["context"],
            assumptions=["assumption"],
            risks=["risk"],
        )

    def handle_params(
        self,
        system_prompt: str,
        chat_messages: object,
        *,
        model: str | None = None,
        temperature: float = 0.2,
        toolbox=None,
        **kwargs: object,
    ) -> dict[str, object]:
        self.calls.append(
            {
                "kind": "handle_params",
                "system_prompt": system_prompt,
                "chat_message": chat_messages,
                "model": model,
                "temperature": temperature,
                "toolbox": getattr(toolbox, "name", None),
                **kwargs,
            }
        )
        return {
            "messages": chat_messages,
            "model": model,
            "temperature": temperature,
            "toolbox": toolbox,
        }

    def call_openai(
        self,
        params: dict[str, object],
        tools_mapping: dict[str, object] | None = None,
        toolbox=None,
        include_tool_meta: bool = False,
    ):
        del toolbox, include_tool_meta
        messages = params.get("messages") or []
        text = str(messages[-1]["content"]).lower() if messages else ""
        if tools_mapping is not None:
            if "show my portfolio" in text and "delegate_to_portfolio_analyst" in tools_mapping:
                tools_mapping["delegate_to_portfolio_analyst"](
                    task_brief="Review the user's current portfolio.",
                    expected_output="Return a concise portfolio summary.",
                    intent_kind=IntentKind.PORTFOLIO_SUMMARY.value,
                    entities=[],
                )
                return _fake_chat_response("Friendly orchestrator answer.")
            if "cancel my oldest order" in text and "delegate_to_order_agent" in tools_mapping:
                tools_mapping["delegate_to_order_agent"](
                    task_brief="Figure out how to cancel the oldest pending order safely.",
                    expected_output="Return the broker action package or the next safe step.",
                    intent_kind=IntentKind.CANCEL_ORDER.value,
                    entities=[],
                )
                return _fake_chat_response("Friendly orchestrator answer.")
            if (
                "what happened in the market today" in text
                and "delegate_to_market_analyst" in tools_mapping
            ):
                tools_mapping["delegate_to_market_analyst"](
                    task_brief="Review today's market context.",
                    expected_output="Summarize the main market drivers.",
                    intent_kind=IntentKind.UNKNOWN.value,
                    entities=[{"key": "domain", "value": "market"}],
                )
                return _fake_chat_response("Friendly orchestrator answer.")
            if "analyze apple earnings" in text and "delegate_to_company_analyst" in tools_mapping:
                tools_mapping["delegate_to_company_analyst"](
                    task_brief="Analyze Apple earnings.",
                    expected_output="Return a company-focused analysis for the user.",
                    intent_kind=IntentKind.ANALYZE_INSTRUMENT.value,
                    entities=[{"key": "ticker", "value": "AAPL"}],
                )
                return _fake_chat_response("Friendly orchestrator answer.")
            if "calculate 2 + 2" in text and "delegate_to_calculator_agent" in tools_mapping:
                tools_mapping["delegate_to_calculator_agent"](
                    task_brief="Compute the requested arithmetic.",
                    expected_output="Return the deterministic calculation result.",
                    intent_kind=IntentKind.CALCULATE.value,
                    entities=[{"key": "expression", "value": "2 + 2"}],
                )
                return _fake_chat_response("Friendly orchestrator answer.")
            if (
                "alert me when tsla goes below 180" in text
                and "delegate_to_scheduler_agent" in tools_mapping
            ):
                tools_mapping["delegate_to_scheduler_agent"](
                    task_brief="Create a deterministic TSLA price monitor.",
                    expected_output="Return the scheduled process id and monitor summary.",
                    intent_kind=IntentKind.MANAGE_SCHEDULED_PROCESSES.value,
                    entities=[{"key": "symbol", "value": "TSLA"}],
                )
                return _fake_chat_response("Friendly orchestrator answer.")
        return _fake_chat_response(
            "I can chat naturally, explain what I do, and delegate portfolio, "
            "order, market, company, guideline-memory, or calculation work when needed."
        )


class SchedulerGenAIClient(FakeGenAIClient):
    def call_openai(
        self,
        params: dict[str, object],
        tools_mapping: dict[str, object] | None = None,
        toolbox=None,
        include_tool_meta: bool = False,
    ):
        del include_tool_meta
        messages = params.get("messages") or []
        text = str(messages[-1]["content"]).lower() if messages else ""
        toolbox_name = getattr(toolbox, "name", None)
        if tools_mapping is not None and toolbox_name == "scheduler_agent":
            if "below 180" in text and "scheduler_instrument_monitor_create" in tools_mapping:
                result = tools_mapping["scheduler_instrument_monitor_create"](
                    title=None,
                    description="Alert when TSLA crosses the requested threshold.",
                    symbol="TSLA",
                    trigger_type="below_price",
                    value=180,
                    lookback_period="1mo",
                    lookback_interval="1d",
                    auto_adjust=False,
                    poll_every_seconds=None,
                    timezone=None,
                    expires_at=None,
                    notification_enabled=True,
                    broker_actions_allowed=False,
                )
                return _fake_chat_response(str(result.output))
            if "alert me when tsla goes below" in text:
                return _fake_chat_response(
                    "Which threshold should I use for the TSLA alert?"
                )
            if "pause the tsla monitor" in text:
                tools_mapping["scheduler_list_processes"](
                    statuses=["active", "paused"],
                    kinds=["instrument_monitor"],
                    limit=20,
                )
                return _fake_chat_response(
                    "I found candidate TSLA monitors. Please provide the exact process_id."
                )
            process_match = re.search(r"sched_[a-z0-9_]+", text)
            if process_match and "pause" in text:
                result = tools_mapping["scheduler_pause_process"](
                    process_id=process_match.group(0)
                )
                return _fake_chat_response(str(result.output))
            if process_match and "archive" in text:
                result = tools_mapping["scheduler_archive_process"](
                    process_id=process_match.group(0)
                )
                return _fake_chat_response(str(result.output))
        return super().call_openai(
            params,
            tools_mapping=tools_mapping,
            toolbox=toolbox,
            include_tool_meta=False,
        )


class BrokerFlowGenAIClient(FakeGenAIClient):
    def generate_structured(
        self,
        schema: type,
        system_prompt: str,
        chat_message: object,
        *,
        model: str | None = None,
        temperature: float = 0.2,
        max_tokens: int | None = None,
    ) -> object:
        self.calls.append(
            {
                "schema": schema.__name__,
                "system_prompt": system_prompt,
                "chat_message": chat_message,
                "model": model,
                "temperature": temperature,
                "max_tokens": max_tokens,
            }
        )
        if schema is AgentReasoningContext:
            return AgentReasoningContext(
                task_interpretation="Prepare a cash-relative broker order.",
                known_facts=["The user asked to use half the available cash."],
                assumptions=[],
                ambiguities=[],
                required_evidence=["broker cash", "broker-native instrument"],
                safety_constraints=["Prepare for Telegram approval only."],
                relevant_capabilities=[
                    "broker_get_portfolio_snapshot",
                    "broker_prepare_order_action",
                ],
                approval_notes=["Telegram callback approval is required."],
                can_proceed=True,
                confidence=0.8,
            )
        if schema is GroupedAgentPlan:
            return GroupedAgentPlan(
                intent={
                    "kind": IntentKind.PROPOSE_TRADE,
                    "entities": [],
                    "confidence": 0.8,
                },
                summary="Read cash, calculate notional, then prepare approval.",
                required_context=["broker cash"],
                action_groups=[
                    {
                        "group_id": "broker_context",
                        "title": "Read broker context",
                        "execution_mode": "sequential",
                        "actions": [
                            {
                                "action_id": "read_cash",
                                "tool_name": "broker_get_portfolio_snapshot",
                                "purpose": "Read available cash.",
                                "expected_output": "Available cash and account currency.",
                                "output_key": "portfolio",
                                "risk_class": "read_only",
                            }
                        ],
                    },
                    {
                        "group_id": "prepare",
                        "title": "Calculate and prepare order",
                        "execution_mode": "sequential",
                        "actions": [
                            {
                                "action_id": "calculate_notional",
                                "purpose": "Calculate half of available cash.",
                                "expected_output": "Resolved decimal notional amount.",
                                "depends_on": ["read_cash"],
                                "output_key": "resolved_notional",
                                "risk_class": "read_only",
                            },
                            {
                                "action_id": "prepare_order",
                                "tool_name": "broker_prepare_order_action",
                                "purpose": "Prepare market buy for approval.",
                                "expected_output": "Pending action and Telegram approval payload.",
                                "depends_on": ["calculate_notional"],
                                "output_key": "approval_payload",
                                "risk_class": "state_changing",
                            },
                        ],
                    },
                ],
                expected_final_output="Approval-ready broker order summary.",
                task_complexity=TaskComplexity.CRITICAL,
            )
        return super().generate_structured(
            schema,
            system_prompt,
            chat_message,
            model=model,
            temperature=temperature,
            max_tokens=max_tokens,
        )


class RecordingGroupedPlanExecutor:
    def __init__(self) -> None:
        self.invocation: AgentInvocationContext | None = None
        self.grouped_plan: GroupedAgentPlan | None = None
        self.toolbox_name: str | None = None
        self.tool_names: set[str] = set()

    def execute(
        self,
        *,
        invocation: AgentInvocationContext,
        reasoning_context: AgentReasoningContext,
        grouped_plan: GroupedAgentPlan,
        toolbox,
        tools_mapping,
    ) -> GroupedPlanExecutionResult:
        del reasoning_context
        self.invocation = invocation
        self.grouped_plan = grouped_plan
        self.toolbox_name = getattr(toolbox, "name", None)
        self.tool_names = set(tools_mapping)
        return GroupedPlanExecutionResult(
            status="ok",
            final_answer="Prepared broker approval from grouped plan.",
            action_summaries=["read cash", "calculated notional", "prepared approval"],
            group_executions=[
                PlanActionGroupExecution(
                    group_id="prepare",
                    title="Prepare approval",
                    execution_mode=PlanExecutionMode.SEQUENTIAL,
                    actions=[
                        PlanActionExecution(
                            action_id="prepare_order",
                            group_id="prepare",
                            tool_name="broker_prepare_order_action",
                            purpose="Prepare market buy for approval.",
                            status="ok",
                            output_summary="Prepared approval.",
                            tool_calls=[
                                {
                                    "tool_name": "broker_prepare_order_action",
                                    "status": "ok",
                                    "telegramApproval": {
                                        "text": "Approve prepared order.",
                                        "actionId": "pa_123",
                                    },
                                }
                            ],
                        )
                    ],
                )
            ],
        )


def _fake_chat_response(text: str):
    return SimpleNamespace(
        choices=[SimpleNamespace(message=SimpleNamespace(content=text, tool_calls=None))]
    )


class FakeExecutorGenAIClient:
    def __init__(self) -> None:
        self.handle_calls: list[dict[str, object]] = []
        self.openai_calls: list[dict[str, object]] = []

    def chat_model_for(self, purpose: str | None = None) -> str:
        return f"{purpose or 'default'}-model"

    def handle_params(
        self,
        system_prompt: str,
        chat_messages: object,
        *,
        model: str | None = None,
        temperature: float = 0.2,
        toolbox=None,
        **kwargs: object,
    ) -> dict[str, object]:
        call = {
            "system_prompt": system_prompt,
            "chat_messages": chat_messages,
            "model": model,
            "temperature": temperature,
            "toolbox": getattr(toolbox, "name", None),
            **kwargs,
        }
        self.handle_calls.append(call)
        return {
            "messages": list(chat_messages) if isinstance(chat_messages, list) else chat_messages,
            "toolbox": toolbox,
            **kwargs,
        }

    def call_openai(
        self,
        params: dict[str, object],
        tools_mapping: dict[str, object] | None = None,
        toolbox=None,
        include_tool_meta: bool = False,
    ):
        del tools_mapping, toolbox, include_tool_meta
        self.openai_calls.append({"params": params})
        messages = params.get("messages")
        if isinstance(messages, list) and params.get("toolbox") is not None:
            messages.append(
                {
                    "role": "tool",
                    "tool_call_id": "call_fake",
                    "content": (
                        '{"status":"ok","data":{"quotes":{"AAPL":{"price":100}}},'
                        '"output":"raw provider payload"}'
                    ),
                }
            )
        return _fake_chat_response(f"Essential action result {len(self.openai_calls)}.")


def _reasoner() -> AgentReasoner:
    return AgentReasoner(FakeGenAIClient())  # type: ignore[arg-type]


def _scheduler_service(tmp_path: Path) -> ScheduledProcessService:
    engine = build_engine(f"sqlite:///{tmp_path / 'scheduler-agent.db'}")
    ensure_schema(engine)
    return ScheduledProcessService(build_session_factory(engine))


class FakeAgentWorkflowBroker:
    reviewed_at = datetime(2026, 4, 27, 12, 0, tzinfo=timezone.utc)

    def get_portfolio_snapshot(self) -> PortfolioSnapshot:
        return PortfolioSnapshot(
            as_of=self.reviewed_at,
            account=AccountSummary(
                id=1,
                currency="EUR",
                cash=Cash(
                    available_to_trade=Decimal("1000"),
                    reserved_for_orders=Decimal("100"),
                ),
                investments=Investments(
                    current_value=Decimal("2500"),
                    total_cost=Decimal("2000"),
                    unrealized_profit_loss=Decimal("500"),
                ),
                total_value=Decimal("3500"),
            ),
            positions=[],
            pending_orders=[
                Order(
                    id=1,
                    ticker="AAPL_US_EQ",
                    currency="EUR",
                    quantity=Decimal("1"),
                    side=OrderSide.BUY,
                    status=OrderStatus.NEW,
                    type=OrderType.LIMIT,
                    limit_price=Decimal("180"),
                    time_in_force=TimeValidity.DAY,
                )
            ],
        )

    def list_pending_orders(self) -> list[Order]:
        return [
            Order(
                id=2,
                ticker="TSLA_US_EQ",
                currency="USD",
                quantity=Decimal("5"),
                filled_quantity=Decimal("1"),
                side=OrderSide.BUY,
                status=OrderStatus.PARTIALLY_FILLED,
                type=OrderType.LIMIT,
                limit_price=Decimal("170"),
                time_in_force=TimeValidity.DAY,
                created_at=self.reviewed_at - timedelta(hours=30),
            )
        ]


def test_chat_history_retains_and_selects_recent_messages() -> None:
    policy = ChatHistoryPolicy(max_messages_per_chat=3, context_messages=2)
    manager = ChatHistoryManager(
        store=InMemoryChatHistoryStore(max_messages_per_chat=policy.max_messages_per_chat),
        policy=policy,
    )

    manager.record_user_message("chat", "one")
    manager.record_assistant_message("chat", "two")
    manager.record_user_message("chat", "three")
    manager.record_assistant_message("chat", "four")
    window = manager.get_context_window("chat")

    assert window.retained_count == 3
    assert window.selected_count == 2
    assert [message.content for message in window.messages] == ["three", "four"]


def test_reasoner_selects_smart_model_for_critical_tasks() -> None:
    fake = FakeGenAIClient()
    reasoner = AgentReasoner(fake)  # type: ignore[arg-type]

    plan = reasoner.build_plan(
        agent_name="order_agent",
        purpose="orders",
        guidelines="be safe",
        toolbox_summary="orders",
        task_complexity=TaskComplexity.CRITICAL,
        user_request="cancel my order",
        chat_history=ChatHistoryWindow(chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.CANCEL_ORDER),
    )

    assert plan.task_complexity == TaskComplexity.CRITICAL
    assert fake.model_purposes == ["smart"]
    assert fake.calls[0]["model"] == "smart-model"


def test_configurable_reasoner_builds_reasoning_context() -> None:
    fake = FakeGenAIClient()
    reasoner = ConfigurableReasonerAgent(fake)  # type: ignore[arg-type]
    history = ChatHistoryWindow(
        chat_id="chat",
        messages=[
            ChatHistoryMessage(
                chat_id="chat",
                role="user",
                content="Earlier context.",
            )
        ],
    )

    context = reasoner.reason(
        AgentInvocationContext(
            user_request="Review today's market.",
            chat_history=history,
            invocation_reason="Market analyst delegated by orchestrator.",
            intent=AgentIntent(kind=IntentKind.UNKNOWN, entities={"domain": "market"}),
            persistent_guidance="Prefer concise answers.",
            agent_name="market_analyst",
            purpose="Analyze market context.",
            guidelines="Use fresh evidence.",
            toolbox_summary="market data tools",
            task_complexity=TaskComplexity.COMPLEX,
        )
    )

    assert context.can_proceed
    assert fake.calls[0]["schema"] == "AgentReasoningContext"
    assert fake.calls[0]["model"] == "smart-model"
    assert fake.calls[0]["chat_message"][0]["content"] == "Earlier context."
    user_prompt = fake.calls[0]["chat_message"][-1]["content"]
    assert "Market analyst delegated by orchestrator." in user_prompt
    assert "Review today's market." in user_prompt
    assert "market_analyst" in fake.calls[0]["system_prompt"]
    assert "market data tools" in fake.calls[0]["system_prompt"]
    assert "Prefer concise answers." in fake.calls[0]["system_prompt"]


def test_configurable_planner_builds_grouped_plan() -> None:
    fake = FakeGenAIClient()
    planner = ConfigurablePlannerAgent(fake)  # type: ignore[arg-type]
    invocation = AgentInvocationContext(
        user_request="Review today's market.",
        invocation_reason="Market analyst delegated by orchestrator.",
        intent=AgentIntent(kind=IntentKind.UNKNOWN, entities={"domain": "market"}),
        agent_name="market_analyst",
        purpose="Analyze market context.",
        guidelines="Use fresh evidence.",
        toolbox_summary="market data and disclosure tools",
        task_complexity=TaskComplexity.COMPLEX,
    )
    reasoning_context = AgentReasoningContext(
        task_interpretation="Review broad market context.",
        required_evidence=["market snapshot", "disclosures"],
        safety_constraints=["read-only only"],
        relevant_capabilities=["market data", "disclosures"],
        can_proceed=True,
        confidence=0.8,
    )

    plan = planner.plan(invocation, reasoning_context=reasoning_context)

    assert fake.calls[0]["schema"] == "GroupedAgentPlan"
    assert fake.calls[0]["model"] == "smart-model"
    assert plan.task_complexity == TaskComplexity.COMPLEX
    assert [group.execution_mode for group in plan.action_groups] == [
        PlanExecutionMode.PARALLEL,
        PlanExecutionMode.SEQUENTIAL,
    ]
    assert plan.action_groups[0].actions[0].output_key == "market_snapshot"
    assert plan.action_groups[1].actions[0].depends_on == ["action_1", "action_2"]
    assert "Review broad market context." in fake.calls[0]["chat_message"][-1]["content"]


def test_grouped_plan_rejects_unsafe_parallel_actions() -> None:
    import pytest

    with pytest.raises(ValueError, match="state_changing_broker_actions_must_be_sequential"):
        GroupedAgentPlan(
            summary="Bad grouped plan.",
            expected_final_output="Approval payload.",
            action_groups=[
                PlanActionGroup(
                    group_id="group_1",
                    title="Unsafe parallel work",
                    execution_mode=PlanExecutionMode.PARALLEL,
                    actions=[
                        PlanAction(
                            action_id="action_1",
                            tool_name="broker_prepare_order_action",
                            purpose="Prepare broker order.",
                            expected_output="Pending action.",
                            risk_class="state_changing",
                        )
                    ],
                )
            ],
        )


def test_grouped_plan_rejects_parallel_internal_dependencies() -> None:
    import pytest

    with pytest.raises(ValueError, match="parallel_group_actions_must_be_independent"):
        GroupedAgentPlan(
            summary="Bad grouped plan.",
            expected_final_output="Summary.",
            action_groups=[
                PlanActionGroup(
                    group_id="group_1",
                    title="Dependent parallel work",
                    execution_mode=PlanExecutionMode.PARALLEL,
                    actions=[
                        PlanAction(
                            action_id="action_1",
                            tool_name="market_get_market_snapshot",
                            purpose="Fetch market context.",
                            expected_output="Market payload.",
                        ),
                        PlanAction(
                            action_id="action_2",
                            purpose="Summarize context.",
                            expected_output="Summary.",
                            depends_on=["action_1"],
                        ),
                    ],
                )
            ],
        )


def test_grouped_plan_executor_controls_parallel_tool_calls_and_context() -> None:
    from t212ai.genai.tools.base import ToolBox, build_tool_index

    tool = {
        "type": "function",
        "function": {
            "name": "market_get_market_snapshot",
            "description": "Fetch market context.",
            "parameters": {
                "type": "object",
                "properties": {},
                "additionalProperties": False,
            },
        },
    }
    toolbox = ToolBox(
        name="market_analyst",
        tools=[tool],
        tools_by_name=build_tool_index([tool]),
    )
    plan = GroupedAgentPlan(
        summary="Review the market.",
        expected_final_output="Concise market answer.",
        action_groups=[
            PlanActionGroup(
                group_id="group_1",
                title="Fetch independent context",
                execution_mode=PlanExecutionMode.PARALLEL,
                actions=[
                    PlanAction(
                        action_id="action_1",
                        tool_name="market_get_market_snapshot",
                        purpose="Fetch first market context.",
                        expected_output="First market context.",
                        risk_class="read_only",
                    ),
                    PlanAction(
                        action_id="action_2",
                        tool_name="market_get_market_snapshot",
                        purpose="Fetch second market context.",
                        expected_output="Second market context.",
                        risk_class="unknown",
                    ),
                ],
            ),
            PlanActionGroup(
                group_id="group_2",
                title="Synthesize",
                execution_mode=PlanExecutionMode.SEQUENTIAL,
                actions=[
                    PlanAction(
                        action_id="action_3",
                        purpose="Synthesize the final answer.",
                        expected_output="Final answer.",
                        depends_on=["action_1", "action_2"],
                    )
                ],
            ),
        ],
    )
    invocation = AgentInvocationContext(
        user_request="What happened in the market today?",
        invocation_reason="Market analyst delegated by orchestrator.",
        intent=AgentIntent(kind=IntentKind.UNKNOWN, entities={"domain": "market"}),
        agent_name="market_analyst",
        purpose="Analyze market context.",
        guidelines="Use market data as context.",
        toolbox_summary="Market data tools.",
        task_complexity=TaskComplexity.COMPLEX,
    )
    reasoning_context = AgentReasoningContext(
        task_interpretation="Review market context.",
        relevant_capabilities=["market data"],
        confidence=0.8,
    )
    fake = FakeExecutorGenAIClient()

    result = GroupedPlanExecutor(fake).execute(
        invocation=invocation,
        reasoning_context=reasoning_context,
        grouped_plan=plan,
        toolbox=toolbox,
        tools_mapping={"market_get_market_snapshot": lambda **_kwargs: None},
    )

    assert result.status == "ok"
    assert [call.get("parallel_tool_calls") for call in fake.handle_calls] == [
        True,
        False,
        None,
    ]
    second_action_messages = fake.handle_calls[1]["chat_messages"]
    assert isinstance(second_action_messages, list)
    assert not any(
        "Completed action action_1" in str(message.get("content", ""))
        for message in second_action_messages
        if isinstance(message, dict)
    )
    third_action_messages = fake.handle_calls[2]["chat_messages"]
    assert isinstance(third_action_messages, list)
    assert any(
        "Completed action action_1" in str(message.get("content", ""))
        for message in third_action_messages
        if isinstance(message, dict)
    )
    assert not any(
        message.get("role") == "tool"
        for message in third_action_messages
        if isinstance(message, dict)
    )
    assert result.group_executions[0].actions[0].tool_calls[0]["data_keys"] == [
        "quotes"
    ]


def test_structured_agent_plan_schema_avoids_free_form_entities() -> None:
    schema = StructuredAgentPlan.model_json_schema()
    entities_schema = schema["$defs"]["StructuredAgentIntent"]["properties"]["entities"]
    item_schema = schema["$defs"]["StructuredIntentEntity"]

    assert entities_schema["type"] == "array"
    assert item_schema["type"] == "object"
    assert item_schema["additionalProperties"] is False


def test_specialist_agent_returns_standardized_response() -> None:
    agent = PortfolioAnalystAgent(_reasoner())

    response = agent.handle(
        AgentRequest(user_message="summarize my portfolio", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.PORTFOLIO_SUMMARY),
    )

    assert response.selected_agent == "portfolio_analyst"
    assert response.plan is not None
    assert "portfolio_analyst prepared a plan" in response.final_answer


def test_market_analyst_agent_exposes_market_analyst_toolbox() -> None:
    from t212ai.agent import MarketAnalystAgent
    from t212ai.genai.tools import build_market_analyst_toolbox

    settings = get_app_settings()
    toolbox = build_market_analyst_toolbox(
        settings=settings,
        assessment=assess_settings(settings),
    )
    agent = MarketAnalystAgent(_reasoner(), toolbox=toolbox)

    assert agent.profile.toolbox is not None
    assert agent.profile.toolbox.name == "market_analyst"
    assert "edgar_company_disclosure_snapshot" in agent.profile.toolbox.tools_by_name
    assert "market_get_volume_monitor" in agent.profile.toolbox.tools_by_name
    assert "market_signal_search" in agent.profile.toolbox.tools_by_name


def test_market_analyst_agent_direct_default_uses_empty_generic_toolbox() -> None:
    from t212ai.agent import MarketAnalystAgent

    agent = MarketAnalystAgent(_reasoner())

    assert agent.profile.toolbox is not None
    assert agent.profile.toolbox.name == "market_analyst"
    assert agent.profile.toolbox.tools_by_name == {}


def test_market_analyst_agent_executes_with_configured_toolbox(monkeypatch) -> None:
    from t212ai.agent import MarketAnalystAgent
    import t212ai.agent.specialists as specialists_module
    from t212ai.genai.tools.base import ToolBox, build_tool_index

    tool = {
        "type": "function",
        "function": {
            "name": "market_get_market_snapshot",
            "description": "Fetch market context.",
            "parameters": {
                "type": "object",
                "properties": {},
                "additionalProperties": False,
            },
        },
    }
    toolbox = ToolBox(
        name="market_analyst",
        tools=[tool],
        tools_by_name=build_tool_index([tool]),
    )
    monkeypatch.setattr(
        specialists_module,
        "build_tool_mapping_for",
        lambda *_args, **_kwargs: {"market_get_market_snapshot": lambda **_kwargs: None},
    )
    agent = MarketAnalystAgent(_reasoner(), toolbox=toolbox)

    response = agent.handle(
        AgentRequest(user_message="general market scan", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.UNKNOWN, entities={"domain": "market"}),
    )

    assert response.selected_agent == "market_analyst"
    assert response.metadata["workflow"] == "market_analysis"
    assert response.final_answer.startswith("I can chat naturally")


def test_market_analyst_agent_uses_configurable_grouped_loop(monkeypatch) -> None:
    from t212ai.agent import MarketAnalystAgent
    import t212ai.agent.specialists as specialists_module
    from t212ai.genai.tools.base import ToolBox, build_tool_index

    tools = [
        {
            "type": "function",
            "function": {
                "name": "market_get_market_snapshot",
                "description": "Fetch market context.",
                "parameters": {
                    "type": "object",
                    "properties": {},
                    "additionalProperties": False,
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "edgar_company_disclosure_snapshot",
                "description": "Fetch disclosure context.",
                "parameters": {
                    "type": "object",
                    "properties": {},
                    "additionalProperties": False,
                },
            },
        },
    ]
    toolbox = ToolBox(
        name="market_analyst",
        tools=tools,
        tools_by_name=build_tool_index(tools),
    )
    monkeypatch.setattr(
        specialists_module,
        "build_tool_mapping_for",
        lambda *_args, **_kwargs: {
            "market_get_market_snapshot": lambda **_kwargs: None,
            "edgar_company_disclosure_snapshot": lambda **_kwargs: None,
        },
    )
    fake = FakeGenAIClient()
    agent = MarketAnalystAgent(
        AgentReasoner(fake),  # type: ignore[arg-type]
        toolbox=toolbox,
        configurable_reasoner_agent=ConfigurableReasonerAgent(fake),  # type: ignore[arg-type]
        configurable_planner_agent=ConfigurablePlannerAgent(fake),  # type: ignore[arg-type]
        grouped_plan_executor=GroupedPlanExecutor(fake),  # type: ignore[arg-type]
    )
    history = ChatHistoryWindow(
        chat_id="chat",
        messages=[
            ChatHistoryMessage(
                chat_id="chat",
                role="user",
                content="Earlier market context request.",
            )
        ],
    )

    response = agent.handle(
        AgentRequest(
            user_message="What happened in the market today?",
            chat_id="chat",
            history=history,
            orchestrator_guidance="Task brief: Review today's market context.",
        ),
        intent=AgentIntent(kind=IntentKind.UNKNOWN, entities={"domain": "market"}),
    )

    assert response.selected_agent == "market_analyst"
    assert response.metadata["workflow"] == "market_analysis"
    assert response.metadata["execution_mode"] == "grouped_plan"
    assert response.plan is not None
    assert response.artifacts["market_analysis"]["reasoning_context"]["can_proceed"]
    assert "grouped_plan" in response.artifacts["market_analysis"]
    assert "execution" in response.artifacts["market_analysis"]
    assert response.artifacts["market_analysis"]["execution"]["action_summaries"]
    schemas = [call.get("schema") for call in fake.calls if "schema" in call]
    assert schemas == ["AgentReasoningContext", "GroupedAgentPlan"]
    reasoning_call = fake.calls[0]
    assert reasoning_call["chat_message"][0]["content"] == "Earlier market context request."
    assert (
        "Task brief: Review today's market context."
        in reasoning_call["chat_message"][-1]["content"]
    )
    assert response.final_answer.strip()


def test_scheduler_agent_creates_instrument_monitor_through_private_tool(
    tmp_path: Path,
) -> None:
    service = _scheduler_service(tmp_path)
    agent = SchedulerAgent(
        AgentReasoner(SchedulerGenAIClient()),  # type: ignore[arg-type]
        scheduled_process_service=service,
        default_timezone="UTC",
        default_poll_every_seconds=300,
    )

    response = agent.handle(
        AgentRequest(user_message="alert me when TSLA goes below 180 today", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.MANAGE_SCHEDULED_PROCESSES),
    )

    processes = service.list_processes(statuses=["active"], kinds=["instrument_monitor"])
    assert response.selected_agent == "scheduler_agent"
    assert response.metadata["workflow"] == "scheduler_delegation"
    assert len(processes) == 1
    assert processes[0].trigger["symbol"] == "TSLA"
    assert processes[0].trigger["type"] == "below_price"
    assert processes[0].safety.broker_actions_allowed is False
    assert "No broker action" in response.final_answer


def test_scheduler_agent_asks_clarification_when_threshold_is_missing(
    tmp_path: Path,
) -> None:
    service = _scheduler_service(tmp_path)
    agent = SchedulerAgent(
        AgentReasoner(SchedulerGenAIClient()),  # type: ignore[arg-type]
        scheduled_process_service=service,
    )

    response = agent.handle(
        AgentRequest(user_message="alert me when TSLA goes below today", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.MANAGE_SCHEDULED_PROCESSES),
    )

    assert "Which threshold" in response.final_answer
    assert service.list_processes() == []


def test_scheduler_agent_lists_candidates_before_fuzzy_pause(tmp_path: Path) -> None:
    service = _scheduler_service(tmp_path)
    process = service.create_process(
        title="TSLA threshold monitor",
        kind="instrument_monitor",
        execution_mode="deterministic",
        schedule={"type": "polling", "pollEverySeconds": 300},
        trigger={"type": "below_price", "symbol": "TSLA", "value": 180},
        inputs={"symbols": ["TSLA"]},
        lifecycle={"completionPolicy": "complete_on_first_match"},
        safety={},
    )
    agent = SchedulerAgent(
        AgentReasoner(SchedulerGenAIClient()),  # type: ignore[arg-type]
        scheduled_process_service=service,
    )

    response = agent.handle(
        AgentRequest(user_message="pause the TSLA monitor", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.MANAGE_SCHEDULED_PROCESSES),
    )

    assert "exact process_id" in response.final_answer
    assert service.get_process(process.process_id).status.value == "active"


def test_scheduler_agent_pauses_and_archives_exact_process_id(tmp_path: Path) -> None:
    service = _scheduler_service(tmp_path)
    process = service.create_process(
        title="TSLA threshold monitor",
        kind="instrument_monitor",
        execution_mode="deterministic",
        schedule={"type": "polling", "pollEverySeconds": 300},
        trigger={"type": "below_price", "symbol": "TSLA", "value": 180},
        inputs={"symbols": ["TSLA"]},
        lifecycle={"completionPolicy": "complete_on_first_match"},
        safety={},
    )
    agent = SchedulerAgent(
        AgentReasoner(SchedulerGenAIClient()),  # type: ignore[arg-type]
        scheduled_process_service=service,
    )

    paused = agent.handle(
        AgentRequest(user_message=f"pause {process.process_id}", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.MANAGE_SCHEDULED_PROCESSES),
    )
    archived = agent.handle(
        AgentRequest(user_message=f"archive {process.process_id}", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.MANAGE_SCHEDULED_PROCESSES),
    )

    assert "Paused scheduled process" in paused.final_answer
    assert "Archived scheduled process" in archived.final_answer
    assert service.get_process(process.process_id).status.value == "archived"


def test_scheduler_agent_returns_unavailable_message_when_service_missing() -> None:
    agent = SchedulerAgent(
        AgentReasoner(SchedulerGenAIClient()),  # type: ignore[arg-type]
        scheduled_process_service=None,
    )

    response = agent.handle(
        AgentRequest(user_message="alert me when TSLA goes below 180", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.MANAGE_SCHEDULED_PROCESSES),
    )

    assert response.metadata["workflow_status"] == "unavailable"
    assert "Scheduler is not configured" in response.final_answer


def test_order_agent_uses_configurable_grouped_loop_with_tool_descriptions() -> None:
    from t212ai.agent import OrderAgent

    fake = BrokerFlowGenAIClient()
    executor = RecordingGroupedPlanExecutor()
    agent = OrderAgent(
        AgentReasoner(fake),  # type: ignore[arg-type]
        toolbox=build_broker_order_action_toolbox(),
        configurable_reasoner_agent=ConfigurableReasonerAgent(fake),  # type: ignore[arg-type]
        configurable_planner_agent=ConfigurablePlannerAgent(fake),  # type: ignore[arg-type]
        grouped_plan_executor=executor,  # type: ignore[arg-type]
        broker_read_service=object(),
        broker_execution_service=object(),
        pending_action_service=object(),  # type: ignore[arg-type]
    )

    response = agent.handle(
        AgentRequest(
            user_message="Prepare a market buy for COIN using half the available cash",
            chat_id="chat",
            orchestrator_guidance="Prepare the broker action safely.",
        ),
        intent=AgentIntent(kind=IntentKind.PROPOSE_TRADE),
    )

    assert response.selected_agent == "order_agent"
    assert response.metadata["workflow"] == "order_action"
    assert response.metadata["execution_mode"] == "grouped_plan"
    assert response.final_answer == "Prepared broker approval from grouped plan."
    assert response.artifacts["telegram_approval_request"]["actionId"] == "pa_123"
    assert executor.toolbox_name == "broker_order_actions"
    assert "broker_prepare_order_action" in executor.tool_names
    assert executor.grouped_plan is not None
    assert executor.grouped_plan.action_groups[1].actions[0].tool_name is None
    assert executor.invocation is not None
    assert "broker_get_portfolio_snapshot" in (executor.invocation.tool_descriptions or "")
    assert "broker_prepare_order_action" in (executor.invocation.tool_descriptions or "")
    assert any("available-cash fractions" in item for item in executor.invocation.reasoning_guidelines)
    assert any("broker-native instrument" in item for item in executor.invocation.reasoning_guidelines)
    assert any("holding-dependent" in item for item in executor.invocation.reasoning_guidelines)
    assert any("buy being submitted and filled" in item for item in executor.invocation.reasoning_guidelines)
    assert any("not_found" in item for item in executor.invocation.planning_guidelines)
    assert any("positive quantityAvailableForTrading" in item for item in executor.invocation.planning_guidelines)
    assert any("refreshed portfolio snapshot" in item for item in executor.invocation.planning_guidelines)
    assert any("cash-relative buy" in item for item in executor.invocation.planning_examples)
    assert any("public-symbol buy" in item for item in executor.invocation.planning_examples)
    assert any("protective sell/stop-limit" in item for item in executor.invocation.planning_examples)

    reasoning_prompt = fake.calls[0]["system_prompt"]
    planner_prompt = fake.calls[1]["system_prompt"]
    assert "Available high-level tool descriptions" in reasoning_prompt
    assert "broker_get_portfolio_snapshot" in reasoning_prompt
    assert "inputs:" not in reasoning_prompt
    assert "Reasoning examples" in reasoning_prompt
    assert "holding-dependent" in reasoning_prompt
    assert "Planning examples" in planner_prompt
    assert "cash-relative buy" in planner_prompt
    assert "protective sell/stop-limit" in planner_prompt
    assert "inputs:" not in planner_prompt


def test_portfolio_agent_executes_summary_workflow_when_available() -> None:
    agent = PortfolioAnalystAgent(
        _reasoner(),
        portfolio_summary_workflow=PortfolioSummaryWorkflow(FakeAgentWorkflowBroker()),
    )

    response = agent.handle(
        AgentRequest(user_message="summarize my portfolio", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.PORTFOLIO_SUMMARY),
    )

    assert response.selected_agent == "portfolio_analyst"
    assert response.plan is not None
    assert response.metadata["workflow"] == "portfolio_summary"
    assert response.artifacts["workflow"] == "portfolio_summary"
    assert "Trading 212 portfolio summary." in response.final_answer


def test_order_agent_executes_pending_orders_workflow_when_available() -> None:
    from t212ai.agent import OrderAgent

    agent = OrderAgent(
        _reasoner(),
        pending_orders_review_workflow=PendingOrdersReviewWorkflow(
            FakeAgentWorkflowBroker(),
            clock=lambda: FakeAgentWorkflowBroker.reviewed_at,
        ),
    )

    response = agent.handle(
        AgentRequest(user_message="review my pending orders", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.REVIEW_PENDING_ORDERS),
    )

    assert response.selected_agent == "order_agent"
    assert response.plan is not None
    assert response.metadata["workflow"] == "pending_orders_review"
    assert "Trading 212 pending orders review." in response.final_answer


def test_order_agent_direct_default_uses_empty_generic_toolbox() -> None:
    from t212ai.agent import OrderAgent

    agent = OrderAgent(_reasoner())

    assert agent.profile.toolbox is not None
    assert agent.profile.toolbox.name == "broker_order_actions"
    assert agent.profile.toolbox.tools_by_name == {}


def test_orchestrator_routes_representative_requests() -> None:
    orchestrator = MainOrchestratorAgent(_reasoner())

    cases = {
        "show my portfolio": "portfolio_analyst",
        "cancel my oldest order": "order_agent",
        "what happened in the market today": "market_analyst",
        "analyze Apple earnings": "company_analyst",
        "calculate 2 + 2": "calculator_agent",
        "hello": "direct",
        "/help": "direct",
    }
    for message, expected_route in cases.items():
        response = orchestrator.handle(AgentRequest(user_message=message, chat_id="chat"))
        assert response.selected_agent == "main_orchestrator"
        if expected_route == "direct":
            assert response.metadata["route"] == "direct"
        else:
            assert response.metadata["route"] == expected_route


def test_orchestrator_routes_scheduler_requests_when_scheduler_agent_is_configured(
    tmp_path: Path,
) -> None:
    service = _scheduler_service(tmp_path)
    reasoner = AgentReasoner(SchedulerGenAIClient())  # type: ignore[arg-type]
    specialists = build_specialist_agents(
        reasoner,
        scheduled_process_service=service,
    )
    orchestrator = MainOrchestratorAgent(reasoner, specialists=specialists)

    response = orchestrator.handle(
        AgentRequest(user_message="alert me when TSLA goes below 180 today", chat_id="chat")
    )

    assert "delegate_to_scheduler_agent" in orchestrator.orchestrator_toolbox.tools_by_name
    assert response.metadata["route"] == "scheduler_agent"


def test_orchestrator_omits_scheduler_tool_when_scheduler_agent_is_missing() -> None:
    orchestrator = MainOrchestratorAgent(_reasoner())

    assert "delegate_to_scheduler_agent" not in orchestrator.orchestrator_toolbox.tools_by_name


def test_classify_message_treats_liquidation_as_order_execution() -> None:
    intent = classify_message("Can you fully liquidate my position in LVMH at mkt price?")

    assert intent.kind == IntentKind.PLACE_ORDER
    assert intent.entities["action"] == "liquidate"


def test_classify_message_keeps_advisory_buy_question_as_trade_discussion() -> None:
    intent = classify_message("Should I buy Apple after earnings?")

    assert intent.kind == IntentKind.PROPOSE_TRADE


def test_classify_message_detects_scheduler_monitoring_requests() -> None:
    intent = classify_message("alert me when TSLA goes below 180 today")

    assert intent.kind == IntentKind.MANAGE_SCHEDULED_PROCESSES


def test_orchestrator_forces_order_agent_for_liquidation_requests() -> None:
    orchestrator = MainOrchestratorAgent(_reasoner())

    response = orchestrator.handle(
        AgentRequest(
            user_message="Can you fully liquidate my position in LVMH at mkt price?",
            chat_id="chat",
        )
    )

    assert response.selected_agent == "main_orchestrator"
    assert response.metadata["route"] == "order_agent"


def test_agent_judge_uses_standardized_critique() -> None:
    judge = AgentJudge(_reasoner())
    response = PortfolioAnalystAgent(_reasoner()).handle(
        AgentRequest(user_message="portfolio", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.PORTFOLIO_SUMMARY),
    )

    critique = judge.review(
        request=AgentRequest(user_message="portfolio", chat_id="chat"),
        response=response,
    )

    assert critique.passed
    assert critique.summary == "Looks complete."


def test_telegram_agent_handler_records_user_and_assistant_history() -> None:
    history = ChatHistoryManager(
        policy=ChatHistoryPolicy(max_messages_per_chat=30, context_messages=16)
    )
    main_agent = MainOrchestratorAgent(_reasoner())
    handler = build_default_message_handler(
        main_agent=main_agent,
        history_manager=history,
    )

    response = handler(
        TelegramInboundMessage(
            chat_id=123,
            text="show my portfolio",
            message_id=1,
        )
    )
    window = history.get_context_window(123)

    assert isinstance(response, TelegramOutboundMessage)
    assert response.text == "Friendly orchestrator answer."
    assert window.retained_count == 2
    assert [message.role for message in window.messages] == ["user", "assistant"]


def test_telegram_agent_handler_falls_back_when_genai_is_not_configured(monkeypatch) -> None:
    import t212ai.telegram.bridge as bridge_module

    monkeypatch.setattr(
        bridge_module,
        "build_runtime",
        lambda: SimpleNamespace(main_orchestrator=None, proposal_service=None),
    )

    handler = build_agent_message_handler_if_configured()
    response = handler(
        TelegramInboundMessage(
            chat_id=123,
            text="show my portfolio",
            message_id=1,
        )
    )

    assert isinstance(response, TelegramOutboundMessage)
    assert "agent runtime is not wired yet" in response.text
