from __future__ import annotations

from pathlib import Path

from t212ai.agent.intents import AgentIntent, IntentKind
from t212ai.agent.orchestrator import MainOrchestratorAgent
from t212ai.agent.reasoning import AgentReasoner
from t212ai.agent.schemas import AgentRequest, AgentResponse
from t212ai.app.runtime import build_runtime
from t212ai.guidelines import (
    GuidelineCategory,
    GuidelineMutationAction,
    GuidelineMutationRequest,
    GuidelineToolRuntime,
    GuidelineMemoryService,
    guideline_create_node,
    guideline_list_nodes,
    guideline_render_preview,
)
from t212ai.guidelines.service import build_empty_guideline_document
from t212ai.persistence.documents import (
    FileBackedStructuredDocumentStore,
    StructuredDocumentNode,
)
from t212ai.agent.planner import AgentPlan


class FakeGenAIClient:
    def __init__(self) -> None:
        self.calls: list[dict[str, object]] = []

    def chat_model_for(self, purpose: str | None = None) -> str:
        return f"{purpose or 'default'}-model"

    def generate_structured(
        self,
        schema: type,
        system_prompt: str,
        chat_message: object,
        *,
        model: str | None = None,
        temperature: float = 0.2,
        max_tokens: int | None = None,
    ) -> object:
        self.calls.append(
            {
                "schema": schema.__name__,
                "system_prompt": system_prompt,
                "chat_message": chat_message,
                "model": model,
                "temperature": temperature,
                "max_tokens": max_tokens,
            }
        )
        if schema is GuidelineMutationRequest:
            text = str(chat_message).lower()
            if "remember that i prefer semiconductors" in text:
                return GuidelineMutationRequest(
                    action=GuidelineMutationAction.CREATE,
                    category=GuidelineCategory.INVESTMENT_PREFERENCE,
                    title="Semiconductor preference",
                    body="Prioritize semiconductor exposure when ideas are otherwise comparable.",
                    priority=8,
                    applies_to=["global", "agent:portfolio", "agent:company"],
                    tags=["semiconductors"],
                    source="user",
                )
            return GuidelineMutationRequest(action=GuidelineMutationAction.LIST)
        return AgentPlan(
            intent=AgentIntent(kind=IntentKind.UNKNOWN),
            summary="Plan generated by fake GenAI.",
            required_context=["context"],
            assumptions=["assumption"],
            risks=["risk"],
        )


def _service(path: Path) -> GuidelineMemoryService:
    return GuidelineMemoryService.from_path(path)


def test_file_backed_structured_document_store_saves_and_loads_json(tmp_path: Path) -> None:
    path = tmp_path / "guidelines.json"
    store = FileBackedStructuredDocumentStore(
        path,
        document_factory=build_empty_guideline_document,
    )
    document = build_empty_guideline_document().model_copy(
        update={
            "nodes": [
                StructuredDocumentNode(
                    id="guideline_001",
                    category="orchestrator_rule",
                    title="Escalate ambiguity",
                    body="Ask for clarification when the user target is ambiguous.",
                    applies_to=["orchestrator"],
                )
            ]
        }
    )

    store.save(document)
    loaded = store.load()

    assert path.exists()
    assert loaded.document_id == "persistent_guidelines"
    assert loaded.nodes[0].title == "Escalate ambiguity"


def test_guideline_memory_service_crud_and_scoped_rendering(tmp_path: Path) -> None:
    service = _service(tmp_path / "guidelines.json")
    created = service.create_node(
        category="investment_preference",
        title="Prefer semiconductors",
        body="Prioritize semiconductor names when the thesis quality is comparable.",
        priority=9,
        tags=["semiconductors"],
        applies_to=["agent:portfolio"],
        source="user",
    )
    service.create_node(
        category="scheduled_rule",
        title="Daily digest timing",
        body="Scheduled digests should run after market close.",
        priority=3,
        applies_to=["schedule:daily_digest"],
        source="system",
    )

    updated = service.update_node(created.id, body="Updated body for portfolio guidance.")
    rendered = service.render_markdown(
        scopes=["global", "agent:portfolio"],
        include_categories=["investment_preference"],
        active_only=True,
    )
    service.archive_node(created.id)
    after_archive = service.render_markdown(
        scopes=["global", "agent:portfolio"],
        include_categories=["investment_preference"],
        active_only=True,
    )

    assert updated.body == "Updated body for portfolio guidance."
    assert "Prefer semiconductors" in rendered
    assert "Daily digest timing" not in rendered
    assert after_archive == ""


def test_guideline_tools_return_verbose_outputs(tmp_path: Path) -> None:
    service = _service(tmp_path / "guidelines.json")
    runtime = GuidelineToolRuntime(service=service)

    create_result = guideline_create_node(
        category="orchestrator_rule",
        title="Route memory requests",
        body="Explicit remember or forget requests should go to the guideline memory agent.",
        priority=5,
        tags=["memory"],
        applies_to=["orchestrator"],
        source="user",
        runtime=runtime,
    )
    list_result = guideline_list_nodes(
        categories=None,
        scopes=None,
        active_only=True,
        runtime=runtime,
    )
    render_result = guideline_render_preview(
        scopes=["orchestrator"],
        include_categories=["investment_preference"],
        active_only=True,
        runtime=runtime,
    )

    assert create_result.status == "ok"
    assert "Created guideline node" in (create_result.output or "")
    assert list_result.status == "ok"
    assert "Nodes:" in (list_result.output or "")
    assert render_result.status == "ok"
    assert "# Persistent Guidelines" in (render_result.output or "")


def test_orchestrator_injects_scoped_persistent_guidelines(tmp_path: Path) -> None:
    service = _service(tmp_path / "guidelines.json")
    service.create_node(
        category="orchestrator_rule",
        title="Escalate ambiguity",
        body="When the target domain is unclear, ask for clarification instead of guessing.",
        priority=7,
        applies_to=["orchestrator"],
        source="user",
    )
    service.create_node(
        category="investment_preference",
        title="Prefer semiconductors",
        body="Favor semiconductor exposure when other factors are balanced.",
        priority=9,
        applies_to=["agent:portfolio"],
        source="user",
    )
    service.create_node(
        category="scheduled_rule",
        title="Daily digest rule",
        body="This is only for scheduled workflows.",
        priority=2,
        applies_to=["schedule:daily_digest"],
        source="system",
    )

    fake = FakeGenAIClient()
    orchestrator = MainOrchestratorAgent(
        AgentReasoner(fake),  # type: ignore[arg-type]
        guideline_service=service,
    )

    response = orchestrator.handle(AgentRequest(user_message="hello there", chat_id="chat"))

    assert response.selected_agent == "main_orchestrator"
    prompt = str(fake.calls[0]["system_prompt"])
    assert "Escalate ambiguity" in prompt
    assert "Prefer semiconductors" in prompt
    assert "Daily digest rule" not in prompt


def test_specialist_receives_scoped_guidelines_only(tmp_path: Path) -> None:
    service = _service(tmp_path / "guidelines.json")
    service.create_node(
        category="agent_rule",
        title="Portfolio risk reminder",
        body="Always highlight concentration risk for large single-name exposures.",
        priority=8,
        applies_to=["agent:portfolio"],
        source="user",
    )
    service.create_node(
        category="orchestrator_rule",
        title="Orchestrator-only rule",
        body="Only for top-level routing.",
        priority=4,
        applies_to=["orchestrator"],
        source="system",
    )

    fake = FakeGenAIClient()
    orchestrator = MainOrchestratorAgent(
        AgentReasoner(fake),  # type: ignore[arg-type]
        guideline_service=service,
    )

    response = orchestrator.handle(
        AgentRequest(user_message="show my portfolio", chat_id="chat")
    )

    assert response.selected_agent == "portfolio_analyst"
    prompt = str(fake.calls[0]["system_prompt"])
    assert "Portfolio risk reminder" in prompt
    assert "Orchestrator-only rule" not in prompt


def test_orchestrator_routes_explicit_memory_requests_to_guideline_agent(tmp_path: Path) -> None:
    service = _service(tmp_path / "guidelines.json")
    fake = FakeGenAIClient()
    orchestrator = MainOrchestratorAgent(
        AgentReasoner(fake),  # type: ignore[arg-type]
        guideline_service=service,
    )

    response = orchestrator.handle(
        AgentRequest(
            user_message="remember that I prefer semiconductors",
            chat_id="chat",
        )
    )
    nodes = service.list_nodes(active_only=False)

    assert response.selected_agent == "guideline_memory_agent"
    assert "Created guideline node" in response.final_answer
    assert len(nodes) == 1
    assert nodes[0].category == "investment_preference"


def test_build_runtime_wires_guideline_memory_service(monkeypatch, tmp_path: Path) -> None:
    path = tmp_path / "runtime-guidelines.json"
    monkeypatch.setenv("GUIDELINE_MEMORY_PATH", str(path))

    runtime = build_runtime()

    assert runtime.settings.guideline_memory_path == str(path)
    assert runtime.guideline_document_store.path == path
    assert runtime.guideline_memory_service.render_markdown() == ""
