from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path
from decimal import Decimal
from types import SimpleNamespace

from t212ai.agent.intents import AgentIntent, IntentKind
from t212ai.agent.planner import StructuredAgentPlan
from t212ai.capabilities import (
    BrokerExecutionService,
    BrokerReadService,
    CommunityResearchService,
    DisclosureService,
    MarketDataService,
    MarketIntelligenceService,
)
from t212ai.app.config import get_app_settings
from t212ai.app.runtime import build_runtime
from t212ai.brokers.trading212.models import (
    AccountSummary,
    Cash,
    Investments,
    PaginatedResponseHistoricalOrder,
    Order,
    OrderSide,
    OrderStatus,
    OrderType,
    PortfolioSnapshot,
    TimeValidity,
)
from t212ai.telegram.bridge import build_agent_message_handler_if_configured
from t212ai.telegram.models import TelegramInboundMessage, TelegramOutboundMessage


class FakeRuntimeGenAIClient:
    def __init__(self, settings) -> None:
        self.settings = settings

    def chat_model_for(self, purpose: str | None = None) -> str:
        return f"{purpose or 'default'}-model"

    def generate_structured(
        self,
        schema: type,
        system_prompt: str,
        chat_message: object,
        *,
        model: str | None = None,
        temperature: float = 0.2,
        max_tokens: int | None = None,
    ) -> object:
        del system_prompt, model, temperature, max_tokens
        return StructuredAgentPlan(
            intent={"kind": IntentKind.UNKNOWN, "entities": [], "confidence": 0.0},
            summary="Plan generated by runtime fake client.",
            required_context=["context"],
            assumptions=["assumption"],
            risks=["risk"],
        )

    def handle_params(
        self,
        system_prompt: str,
        chat_messages: object,
        *,
        model: str | None = None,
        temperature: float = 0.2,
        toolbox=None,
        **kwargs: object,
    ) -> dict[str, object]:
        del system_prompt, model, temperature, toolbox, kwargs
        return {"messages": chat_messages}

    def call_openai(
        self,
        params: dict[str, object],
        tools_mapping: dict[str, object] | None = None,
        toolbox=None,
        include_tool_meta: bool = False,
    ):
        del toolbox, include_tool_meta
        messages = params.get("messages") or []
        text = str(messages[-1]["content"]).lower() if messages else ""
        if tools_mapping is not None and "show my portfolio" in text:
            tools_mapping["delegate_to_portfolio_analyst"](
                task_brief="Review the user's current portfolio.",
                expected_output="Return a concise portfolio summary.",
                intent_kind=IntentKind.PORTFOLIO_SUMMARY.value,
                entities=[],
            )
        return SimpleNamespace(
            choices=[
                SimpleNamespace(
                    message=SimpleNamespace(
                        content="Friendly orchestrator answer.",
                        tool_calls=None,
                    )
                )
            ]
        )


class FakeTrading212Client:
    reviewed_at = datetime(2026, 4, 27, 12, 0, tzinfo=timezone.utc)

    @classmethod
    def from_settings(cls, settings=None):
        del settings
        return cls()

    def get_account_summary(self):
        return AccountSummary(
            id=1,
            currency="EUR",
            cash=Cash(
                available_to_trade=Decimal("1000"),
                reserved_for_orders=Decimal("200"),
            ),
            investments=Investments(
                current_value=Decimal("2500"),
                total_cost=Decimal("2200"),
                unrealized_profit_loss=Decimal("300"),
            ),
            total_value=Decimal("3500"),
        )

    def list_positions(self):
        return []

    def list_pending_orders(self):
        return [
            Order(
                id=22,
                ticker="MSFT_US_EQ",
                currency="EUR",
                quantity=Decimal("1"),
                side=OrderSide.BUY,
                status=OrderStatus.NEW,
                type=OrderType.LIMIT,
                limit_price=Decimal("320"),
                time_in_force=TimeValidity.DAY,
                created_at=self.reviewed_at - timedelta(hours=2),
            )
        ]

    def get_order(self, order_id: int):
        raise NotImplementedError

    def list_historical_orders(self, *, cursor=None, ticker=None, limit=None):
        del cursor, ticker, limit
        return PaginatedResponseHistoricalOrder(items=[])

    def place_market_order(self, request):
        raise NotImplementedError

    def place_limit_order(self, request):
        raise NotImplementedError

    def place_stop_order(self, request):
        raise NotImplementedError

    def place_stop_limit_order(self, request):
        raise NotImplementedError

    def cancel_order(self, order_id: int):
        raise NotImplementedError


class FakeAlphaVantageClient:
    @classmethod
    def from_settings(cls, settings=None):
        del settings
        return cls()


class FakeAlpacaMarketDataClient:
    @classmethod
    def from_settings(cls, settings=None):
        del settings
        return cls()

    def get_quote_snapshot(self, symbols):
        from t212ai.capabilities.market_data_models import MarketQuoteSnapshotResult

        return MarketQuoteSnapshotResult(
            quotes={
                symbol: {
                    "symbol": symbol,
                    "price": 101.0,
                    "change_pct": 1.25,
                    "volume": 1000.0,
                    "currency": "USD",
                    "exchange": "IEX",
                    "market_state": None,
                }
                for symbol in symbols
            },
            errors={},
            meta={"provider": "alpaca", "feed": "iex"},
        )

    def get_price_history(self, symbols, **_kwargs):
        from t212ai.capabilities.market_data_models import MarketPriceHistoryResult

        return MarketPriceHistoryResult(
            series={
                symbol: [
                    {
                        "timestamp": "2026-01-01T00:00:00Z",
                        "open": 100,
                        "high": 102,
                        "low": 99,
                        "close": 101,
                        "volume": 1000,
                    }
                ]
                for symbol in symbols
            },
            errors={},
            meta={"provider": "alpaca", "feed": "iex"},
        )

    def search_symbols(self, query, **_kwargs):
        from t212ai.capabilities.market_data_models import MarketSymbolSearchResult

        return MarketSymbolSearchResult(
            query=query,
            candidates=[
                {
                    "symbol": "AAPL",
                    "name": "Apple Inc.",
                    "exchange": "NASDAQ",
                    "asset_class": "us_equity",
                    "status": "active",
                    "tradable": True,
                }
            ],
            meta={"provider": "alpaca"},
        )


class FakeAlpacaBrokerClient:
    reviewed_at = datetime(2026, 4, 27, 12, 0, tzinfo=timezone.utc)

    @classmethod
    def from_settings(cls, settings=None):
        del settings
        return cls()

    def get_account(self):
        return {
            "id": "account-1",
            "account_number": "PA1234567",
            "currency": "USD",
            "buying_power": "5000",
            "portfolio_value": "7500",
        }

    def list_positions(self):
        return [
            {
                "symbol": "AAPL",
                "qty": "2",
                "qty_available": "2",
                "avg_entry_price": "150",
                "current_price": "175",
                "market_value": "350",
                "cost_basis": "300",
                "unrealized_pl": "50",
            }
        ]

    def list_orders(self, *, status: str, limit: int | None = None, ticker: str | None = None, cursor=None):
        del limit, ticker, cursor
        if status == "open":
            return [
                {
                    "id": "alpaca-open-1",
                    "symbol": "MSFT",
                    "qty": "1",
                    "filled_qty": "0",
                    "side": "buy",
                    "status": "new",
                    "type": "limit",
                    "limit_price": "320",
                    "time_in_force": "day",
                    "created_at": self.reviewed_at.isoformat().replace("+00:00", "Z"),
                    "extended_hours": False,
                }
            ]
        return []

    def get_order(self, order_ref: str):
        return {
            "id": order_ref,
            "symbol": "MSFT",
            "qty": "1",
            "side": "buy",
            "status": "new",
            "type": "limit",
            "time_in_force": "day",
        }

    def place_order(self, payload):
        return {
            "id": "alpaca-order-1",
            "symbol": payload["symbol"],
            "qty": payload["qty"],
            "filled_qty": "0",
            "side": payload["side"],
            "status": "accepted",
            "type": payload["type"],
            "time_in_force": payload["time_in_force"],
            "limit_price": payload.get("limit_price"),
            "stop_price": payload.get("stop_price"),
            "extended_hours": payload.get("extended_hours"),
            "client_order_id": payload.get("client_order_id"),
            "created_at": self.reviewed_at.isoformat().replace("+00:00", "Z"),
        }

    def cancel_order(self, order_ref: str):
        del order_ref


class FakeRedditClient:
    @classmethod
    def from_settings(cls, settings=None):
        del settings
        return cls()


def test_build_runtime_records_genai_error_when_llm_is_missing(tmp_path: Path) -> None:
    settings = get_app_settings(
        env={
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )

    runtime = build_runtime(settings)

    assert runtime.guideline_memory_service.render_markdown() == ""
    assert runtime.history_manager is not None
    assert runtime.db_engine is not None
    assert runtime.db_session_factory is not None
    assert runtime.pending_action_service is not None
    assert runtime.proposal_service is not None
    assert runtime.market_signal_service is not None
    assert runtime.scheduled_process_service is not None
    assert runtime.scheduler_notification_service is None
    assert runtime.calculator_service is not None
    assert runtime.market_data_service is not None
    assert isinstance(runtime.market_data_service, MarketDataService)
    assert runtime.market_intelligence_service is None
    assert runtime.community_research_service is None
    assert runtime.disclosure_service is not None
    assert isinstance(runtime.disclosure_service, DisclosureService)
    assert runtime.search_service is None
    assert runtime.broker_read_service is None
    assert runtime.broker_execution_service is None
    assert runtime.capability_registry["market_data"].selected_provider == "yahoo"
    assert runtime.capability_registry["market_data"].ready
    assert runtime.capability_registry["market_signal_memory"].ready
    assert runtime.capability_registry["scheduled_processes"].ready
    assert not runtime.capability_registry["scheduler_notifications"].ready
    assert runtime.capability_registry["scheduler_instrument_monitor"].ready
    assert not runtime.capability_registry["scheduler_delegate"].ready
    assert not runtime.capability_registry["scheduler_company_event_analyst"].ready
    assert not runtime.capability_registry["scheduler_market_regime_monitor"].ready
    assert not runtime.capability_registry["scheduler_market_signal_capture"].ready
    assert not runtime.capability_registry["scheduler_trade_setup_monitor"].ready
    assert runtime.capability_registry["disclosure"].selected_provider == "sec_edgar"
    assert runtime.capability_registry["disclosure"].ready
    assert runtime.capability_registry["broker_read"].implementation is None
    assert runtime.specialist_tooling is not None
    assert runtime.specialist_tooling.order_toolbox is None
    assert "SEC EDGAR" not in runtime.specialist_tooling.market_toolbox_summary
    assert "official disclosure activity" in runtime.specialist_tooling.market_toolbox_summary
    assert "yahoo_market_context" not in runtime.toolboxes
    assert set(runtime.toolboxes["market_analyst"].tools_by_name) == {
        "market_get_market_snapshot",
        "market_get_volume_monitor",
        "edgar_recent_ownership_activity",
        "edgar_recent_major_stake_activity",
        "edgar_company_disclosure_snapshot",
        "market_signal_search",
        "market_signal_create",
        "market_signal_archive",
    }
    assert runtime.sec_edgar_client is not None
    assert runtime.insider_manager is not None
    assert runtime.genai_client is None
    assert runtime.configurable_reasoner_agent is None
    assert runtime.configurable_planner_agent is None
    assert runtime.grouped_plan_executor is None
    assert runtime.specialist_agents is None
    assert runtime.company_agent is None
    assert runtime.market_agent is None
    assert runtime.calculator_agent is None
    assert runtime.scheduler_agent is None
    assert runtime.main_orchestrator is None
    assert "genai_client" in runtime.component_errors
    assert not runtime.has_agent_runtime


def test_build_runtime_disables_scheduler_when_database_is_unavailable(tmp_path: Path) -> None:
    settings = get_app_settings(
        env={
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": "",
        }
    )

    runtime = build_runtime(settings)

    assert runtime.db_engine is None
    assert runtime.db_session_factory is None
    assert runtime.scheduled_process_service is None
    assert runtime.scheduler_notification_service is None
    assert not runtime.capability_registry["scheduled_processes"].ready
    assert runtime.capability_registry["scheduled_processes"].selected_provider is None
    assert not runtime.capability_registry["scheduler_notifications"].ready
    assert not runtime.capability_registry["scheduler_instrument_monitor"].ready
    assert not runtime.capability_registry["scheduler_delegate"].ready
    assert not runtime.capability_registry["scheduler_company_event_analyst"].ready
    assert not runtime.capability_registry["scheduler_market_regime_monitor"].ready
    assert not runtime.capability_registry["scheduler_market_signal_capture"].ready
    assert not runtime.capability_registry["scheduler_trade_setup_monitor"].ready
    assert runtime.scheduler_agent is None
    assert "database" in runtime.component_errors


def test_build_runtime_wires_scheduler_notifications_when_telegram_is_configured(
    tmp_path: Path,
) -> None:
    settings = get_app_settings(
        env={
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
            "TELEGRAM_BOT_TOKEN": "telegram-token",
            "TELEGRAM_ALLOWED_CHAT_ID": "123,456",
        }
    )

    runtime = build_runtime(settings)

    assert runtime.scheduled_process_service is not None
    assert runtime.scheduler_notification_service is not None
    assert runtime.telegram_scheduler_notifier is not None
    assert runtime.scheduler_notification_service.chat_history_journal is not None
    assert runtime.capability_registry["scheduler_notifications"].ready
    assert runtime.capability_registry["scheduler_notifications"].selected_provider == "telegram"


def test_build_runtime_wires_agent_stack_when_llm_is_configured(
    monkeypatch,
    tmp_path: Path,
) -> None:
    import t212ai.app.runtime as runtime_module

    monkeypatch.setattr(runtime_module, "GenAIClient", FakeRuntimeGenAIClient)
    settings = get_app_settings(
        env={
            "LLM_PROVIDER": "openai",
            "OPENAI_API_KEY": "openai-key",
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )

    runtime = build_runtime(settings)

    assert runtime.genai_client is not None
    assert runtime.agent_reasoner is not None
    assert runtime.configurable_reasoner_agent is not None
    assert runtime.configurable_planner_agent is not None
    assert runtime.grouped_plan_executor is not None
    assert runtime.agent_judge is not None
    assert runtime.main_orchestrator is not None
    assert runtime.specialist_agents is not None
    assert runtime.company_agent is not None
    assert runtime.market_agent is not None
    assert runtime.scheduler_agent is not None
    assert runtime.db_engine is not None
    assert runtime.db_session_factory is not None
    assert runtime.pending_action_service is not None
    assert runtime.proposal_service is not None
    assert runtime.market_signal_service is not None
    assert runtime.scheduled_process_service is not None
    assert runtime.calculator_service is not None
    assert runtime.calculator_agent is not None
    assert runtime.market_data_service is not None
    assert runtime.disclosure_service is not None
    assert runtime.sec_edgar_client is not None
    assert runtime.insider_manager is not None
    assert runtime.has_agent_runtime
    assert runtime.capability_registry["scheduler_delegate"].ready
    assert runtime.capability_registry["scheduler_company_event_analyst"].ready
    assert runtime.capability_registry["scheduler_market_regime_monitor"].ready
    assert runtime.capability_registry["scheduler_market_signal_capture"].ready
    assert not runtime.capability_registry["scheduler_trade_setup_monitor"].ready
    assert runtime.component_errors == {}


def test_build_runtime_builds_optional_provider_stacks(
    monkeypatch,
    tmp_path: Path,
) -> None:
    import t212ai.app.runtime as runtime_module

    monkeypatch.setattr(runtime_module, "GenAIClient", FakeRuntimeGenAIClient)
    monkeypatch.setattr(runtime_module, "Trading212Client", FakeTrading212Client)
    monkeypatch.setattr(runtime_module, "AlphaVantageClient", FakeAlphaVantageClient)
    monkeypatch.setattr(runtime_module, "RedditClient", FakeRedditClient)
    settings = get_app_settings(
        env={
            "LLM_PROVIDER": "openai",
            "OPENAI_API_KEY": "openai-key",
            "BROKER_PROVIDER": "trading212",
            "T212_API_KEY": "t212-key",
            "T212_API_SECRET": "t212-secret",
            "YAHOO_ENABLED": "true",
            "ALPHA_VANTAGE_ENABLED": "true",
            "ALPHA_VANTAGE_API_KEY": "alpha-key",
            "REDDIT_ENABLED": "true",
            "REDDIT_CLIENT_ID": "reddit-id",
            "REDDIT_CLIENT_SECRET": "reddit-secret",
            "REDDIT_REFRESH_TOKEN": "refresh-token",
            "REDDIT_USER_AGENT": "server:t212ai:test (by /u/tester)",
            "TELEGRAM_BOT_TOKEN": "telegram-token",
            "TELEGRAM_ALLOWED_CHAT_ID": "123",
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )

    runtime = build_runtime(settings)

    assert runtime.trading212_client is not None
    assert runtime.trading212_service is not None
    assert runtime.broker_read_service is not None
    assert runtime.broker_execution_service is not None
    assert isinstance(runtime.broker_read_service, BrokerReadService)
    assert isinstance(runtime.broker_execution_service, BrokerExecutionService)
    assert runtime.pending_action_service is not None
    assert runtime.proposal_service is not None
    assert runtime.market_signal_service is not None
    assert runtime.scheduled_process_service is not None
    assert runtime.reconciliation_service is not None
    assert runtime.portfolio_summary_workflow is not None
    assert runtime.pending_orders_review_workflow is not None
    assert runtime.yahoo_client is not None
    assert runtime.market_data_service is not None
    assert isinstance(runtime.market_data_service, MarketDataService)
    assert runtime.alpha_vantage_client is not None
    assert runtime.market_intelligence_service is not None
    assert isinstance(runtime.market_intelligence_service, MarketIntelligenceService)
    assert runtime.reddit_client is not None
    assert runtime.reddit_service is not None
    assert runtime.community_research_service is not None
    assert isinstance(runtime.community_research_service, CommunityResearchService)
    assert runtime.sec_edgar_client is not None
    assert runtime.insider_manager is not None
    assert runtime.disclosure_service is not None
    assert isinstance(runtime.disclosure_service, DisclosureService)
    assert runtime.capability_registry["broker_read"].ready
    assert runtime.capability_registry["broker_execution"].ready
    assert runtime.capability_registry["market_intelligence"].ready
    assert runtime.capability_registry["market_signal_memory"].ready
    assert runtime.capability_registry["scheduled_processes"].ready
    assert runtime.capability_registry["scheduler_instrument_monitor"].ready
    assert runtime.capability_registry["scheduler_delegate"].ready
    assert runtime.capability_registry["scheduler_company_event_analyst"].ready
    assert runtime.capability_registry["scheduler_market_regime_monitor"].ready
    assert runtime.capability_registry["scheduler_market_signal_capture"].ready
    assert runtime.capability_registry["scheduler_notifications"].ready
    assert runtime.capability_registry["scheduler_trade_setup_monitor"].ready
    assert runtime.capability_registry["community_research"].ready
    assert not runtime.capability_registry["search"].ready
    market_tools = runtime.toolboxes["market_analyst"].tools_by_name
    assert "alpha_vantage_most_actively_traded" in market_tools
    assert "market_signal_search" in market_tools
    assert "searxng_search" not in market_tools
    assert runtime.specialist_tooling is not None
    assert runtime.specialist_tooling.order_toolbox is not None
    assert runtime.specialist_tooling.order_toolbox.name == "broker_order_actions"
    assert "Alpha Vantage" not in runtime.specialist_tooling.market_toolbox_summary
    assert "official disclosure activity" in runtime.specialist_tooling.market_toolbox_summary
    assert "yahoo_market_context" not in runtime.toolboxes
    assert runtime.has_broker_runtime
    assert runtime.has_market_data_runtime


def test_build_runtime_selects_alpaca_market_data_when_configured(
    monkeypatch,
    tmp_path: Path,
) -> None:
    import t212ai.alpaca.market_data as alpaca_market_data_module

    monkeypatch.setattr(
        alpaca_market_data_module,
        "AlpacaMarketDataClient",
        FakeAlpacaMarketDataClient,
    )
    settings = get_app_settings(
        env={
            "MARKET_DATA_PROVIDER": "alpaca",
            "ALPACA_API_KEY": "alpaca-key",
            "ALPACA_API_SECRET": "alpaca-secret",
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )

    runtime = build_runtime(settings)

    assert runtime.alpaca_market_data_client is not None
    assert runtime.market_data_service is not None
    assert isinstance(runtime.market_data_service, MarketDataService)
    assert runtime.capability_registry["market_data"].selected_provider == "alpaca"
    assert runtime.capability_registry["market_data"].ready


def test_build_runtime_selects_alpaca_broker_when_configured(
    monkeypatch,
    tmp_path: Path,
) -> None:
    import t212ai.app.runtime as runtime_module

    monkeypatch.setattr(runtime_module, "AlpacaBrokerClient", FakeAlpacaBrokerClient)
    settings = get_app_settings(
        env={
            "BROKER_PROVIDER": "alpaca",
            "ALPACA_API_KEY": "alpaca-key",
            "ALPACA_API_SECRET": "alpaca-secret",
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )

    runtime = build_runtime(settings)

    assert runtime.alpaca_broker_client is not None
    assert runtime.alpaca_broker_service is not None
    assert runtime.broker_read_service is not None
    assert runtime.broker_execution_service is not None
    assert isinstance(runtime.broker_read_service, BrokerReadService)
    assert isinstance(runtime.broker_execution_service, BrokerExecutionService)
    assert runtime.reconciliation_service is not None
    assert runtime.capability_registry["broker_read"].selected_provider == "alpaca"
    assert runtime.capability_registry["broker_read"].ready


def test_runtime_backed_agent_handler_reuses_runtime_history(
    monkeypatch,
    tmp_path: Path,
) -> None:
    import t212ai.app.runtime as runtime_module

    monkeypatch.setattr(runtime_module, "GenAIClient", FakeRuntimeGenAIClient)
    settings = get_app_settings(
        env={
            "LLM_PROVIDER": "openai",
            "OPENAI_API_KEY": "openai-key",
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )
    runtime = build_runtime(settings)

    handler = build_agent_message_handler_if_configured(runtime=runtime)
    response = handler(
        TelegramInboundMessage(
            chat_id=123,
            text="show my portfolio",
            message_id=1,
        )
    )
    history = runtime.history_manager.get_context_window(123)

    assert isinstance(response, TelegramOutboundMessage)
    assert response.text == "Friendly orchestrator answer."
    assert history.retained_count == 2
    assert [message.role for message in history.messages] == ["user", "assistant"]


def test_runtime_backed_agent_handler_uses_portfolio_workflow_when_broker_is_configured(
    monkeypatch,
    tmp_path: Path,
) -> None:
    import t212ai.app.runtime as runtime_module

    monkeypatch.setattr(runtime_module, "GenAIClient", FakeRuntimeGenAIClient)
    monkeypatch.setattr(runtime_module, "Trading212Client", FakeTrading212Client)
    settings = get_app_settings(
        env={
            "LLM_PROVIDER": "openai",
            "OPENAI_API_KEY": "openai-key",
            "BROKER_PROVIDER": "trading212",
            "T212_API_KEY": "t212-key",
            "T212_API_SECRET": "t212-secret",
            "GUIDELINE_MEMORY_PATH": str(tmp_path / "guidelines.json"),
            "DATABASE_URL": f"sqlite:///{tmp_path / 'app.db'}",
        }
    )
    runtime = build_runtime(settings)

    handler = build_agent_message_handler_if_configured(runtime=runtime)
    response = handler(
        TelegramInboundMessage(
            chat_id=123,
            text="show my portfolio",
            message_id=1,
        )
    )

    assert isinstance(response, TelegramOutboundMessage)
    assert response.text == "Friendly orchestrator answer."
