from __future__ import annotations

from datetime import datetime, timedelta, timezone
from decimal import Decimal

from t212ai.agent import (
    AgentJudge,
    AgentReasoner,
    AgentRequest,
    ChatHistoryManager,
    ChatHistoryPolicy,
    InMemoryChatHistoryStore,
    MainOrchestratorAgent,
    PortfolioAnalystAgent,
    TaskComplexity,
)
from t212ai.agent.history import ChatHistoryWindow
from t212ai.agent.intents import AgentIntent, IntentKind
from t212ai.agent.planner import AgentPlan
from t212ai.agent.schemas import AgentCritique
from t212ai.brokers.trading212.models import (
    AccountSummary,
    Cash,
    Investments,
    Order,
    OrderSide,
    OrderStatus,
    OrderType,
    PortfolioSnapshot,
    TimeValidity,
)
from t212ai.telegram.bridge import (
    build_agent_message_handler_if_configured,
    build_default_message_handler,
)
from t212ai.telegram.models import TelegramInboundMessage, TelegramOutboundMessage
from t212ai.workflows import PendingOrdersReviewWorkflow, PortfolioSummaryWorkflow


class FakeGenAIClient:
    def __init__(self) -> None:
        self.calls: list[dict[str, object]] = []
        self.model_purposes: list[str] = []

    def chat_model_for(self, purpose: str | None = None) -> str:
        resolved = purpose or "default"
        self.model_purposes.append(resolved)
        return f"{resolved}-model"

    def generate_structured(
        self,
        schema: type,
        system_prompt: str,
        chat_message: object,
        *,
        model: str | None = None,
        temperature: float = 0.2,
        max_tokens: int | None = None,
    ) -> object:
        self.calls.append(
            {
                "schema": schema.__name__,
                "system_prompt": system_prompt,
                "chat_message": chat_message,
                "model": model,
                "temperature": temperature,
                "max_tokens": max_tokens,
            }
        )
        if schema is AgentCritique:
            return AgentCritique(
                passed=True,
                summary="Looks complete.",
                confidence=0.9,
            )
        return AgentPlan(
            intent=AgentIntent(kind=IntentKind.UNKNOWN),
            summary="Plan generated by fake GenAI.",
            required_context=["context"],
            assumptions=["assumption"],
            risks=["risk"],
        )


def _reasoner() -> AgentReasoner:
    return AgentReasoner(FakeGenAIClient())  # type: ignore[arg-type]


class FakeAgentWorkflowBroker:
    reviewed_at = datetime(2026, 4, 27, 12, 0, tzinfo=timezone.utc)

    def get_portfolio_snapshot(self) -> PortfolioSnapshot:
        return PortfolioSnapshot(
            as_of=self.reviewed_at,
            account=AccountSummary(
                id=1,
                currency="EUR",
                cash=Cash(
                    available_to_trade=Decimal("1000"),
                    reserved_for_orders=Decimal("100"),
                ),
                investments=Investments(
                    current_value=Decimal("2500"),
                    total_cost=Decimal("2000"),
                    unrealized_profit_loss=Decimal("500"),
                ),
                total_value=Decimal("3500"),
            ),
            positions=[],
            pending_orders=[
                Order(
                    id=1,
                    ticker="AAPL_US_EQ",
                    currency="EUR",
                    quantity=Decimal("1"),
                    side=OrderSide.BUY,
                    status=OrderStatus.NEW,
                    type=OrderType.LIMIT,
                    limit_price=Decimal("180"),
                    time_in_force=TimeValidity.DAY,
                )
            ],
        )

    def list_pending_orders(self) -> list[Order]:
        return [
            Order(
                id=2,
                ticker="TSLA_US_EQ",
                currency="USD",
                quantity=Decimal("5"),
                filled_quantity=Decimal("1"),
                side=OrderSide.BUY,
                status=OrderStatus.PARTIALLY_FILLED,
                type=OrderType.LIMIT,
                limit_price=Decimal("170"),
                time_in_force=TimeValidity.DAY,
                created_at=self.reviewed_at - timedelta(hours=30),
            )
        ]


def test_chat_history_retains_and_selects_recent_messages() -> None:
    policy = ChatHistoryPolicy(max_messages_per_chat=3, context_messages=2)
    manager = ChatHistoryManager(
        store=InMemoryChatHistoryStore(max_messages_per_chat=policy.max_messages_per_chat),
        policy=policy,
    )

    manager.record_user_message("chat", "one")
    manager.record_assistant_message("chat", "two")
    manager.record_user_message("chat", "three")
    manager.record_assistant_message("chat", "four")
    window = manager.get_context_window("chat")

    assert window.retained_count == 3
    assert window.selected_count == 2
    assert [message.content for message in window.messages] == ["three", "four"]


def test_reasoner_selects_smart_model_for_critical_tasks() -> None:
    fake = FakeGenAIClient()
    reasoner = AgentReasoner(fake)  # type: ignore[arg-type]

    plan = reasoner.build_plan(
        agent_name="order_agent",
        purpose="orders",
        guidelines="be safe",
        toolbox_summary="orders",
        task_complexity=TaskComplexity.CRITICAL,
        user_request="cancel my order",
        chat_history=ChatHistoryWindow(chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.CANCEL_ORDER),
    )

    assert plan.task_complexity == TaskComplexity.CRITICAL
    assert fake.model_purposes == ["smart"]
    assert fake.calls[0]["model"] == "smart-model"


def test_specialist_agent_returns_standardized_response() -> None:
    agent = PortfolioAnalystAgent(_reasoner())

    response = agent.handle(
        AgentRequest(user_message="summarize my portfolio", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.PORTFOLIO_SUMMARY),
    )

    assert response.selected_agent == "portfolio_analyst"
    assert response.plan is not None
    assert "portfolio_analyst prepared a plan" in response.final_answer


def test_portfolio_agent_executes_summary_workflow_when_available() -> None:
    agent = PortfolioAnalystAgent(
        _reasoner(),
        portfolio_summary_workflow=PortfolioSummaryWorkflow(FakeAgentWorkflowBroker()),
    )

    response = agent.handle(
        AgentRequest(user_message="summarize my portfolio", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.PORTFOLIO_SUMMARY),
    )

    assert response.selected_agent == "portfolio_analyst"
    assert response.plan is not None
    assert response.metadata["workflow"] == "portfolio_summary"
    assert response.artifacts["workflow"] == "portfolio_summary"
    assert "Trading 212 portfolio summary." in response.final_answer


def test_order_agent_executes_pending_orders_workflow_when_available() -> None:
    from t212ai.agent import OrderAgent

    agent = OrderAgent(
        _reasoner(),
        pending_orders_review_workflow=PendingOrdersReviewWorkflow(
            FakeAgentWorkflowBroker(),
            clock=lambda: FakeAgentWorkflowBroker.reviewed_at,
        ),
    )

    response = agent.handle(
        AgentRequest(user_message="review my pending orders", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.REVIEW_PENDING_ORDERS),
    )

    assert response.selected_agent == "order_agent"
    assert response.plan is not None
    assert response.metadata["workflow"] == "pending_orders_review"
    assert "Trading 212 pending orders review." in response.final_answer


def test_orchestrator_routes_representative_requests() -> None:
    orchestrator = MainOrchestratorAgent(_reasoner())

    cases = {
        "show my portfolio": "portfolio_analyst",
        "cancel my oldest order": "order_agent",
        "what happened in the market today": "market_analyst",
        "analyze Apple earnings": "company_analyst",
        "calculate 2 + 2": "main_orchestrator",
        "hello": "main_orchestrator",
        "/help": "main_orchestrator",
    }
    for message, expected_agent in cases.items():
        response = orchestrator.handle(AgentRequest(user_message=message, chat_id="chat"))
        assert response.selected_agent == expected_agent


def test_agent_judge_uses_standardized_critique() -> None:
    judge = AgentJudge(_reasoner())
    response = PortfolioAnalystAgent(_reasoner()).handle(
        AgentRequest(user_message="portfolio", chat_id="chat"),
        intent=AgentIntent(kind=IntentKind.PORTFOLIO_SUMMARY),
    )

    critique = judge.review(
        request=AgentRequest(user_message="portfolio", chat_id="chat"),
        response=response,
    )

    assert critique.passed
    assert critique.summary == "Looks complete."


def test_telegram_agent_handler_records_user_and_assistant_history() -> None:
    history = ChatHistoryManager(
        policy=ChatHistoryPolicy(max_messages_per_chat=30, context_messages=16)
    )
    main_agent = MainOrchestratorAgent(_reasoner())
    handler = build_default_message_handler(
        main_agent=main_agent,
        history_manager=history,
    )

    response = handler(
        TelegramInboundMessage(
            chat_id=123,
            text="show my portfolio",
            message_id=1,
        )
    )
    window = history.get_context_window(123)

    assert isinstance(response, TelegramOutboundMessage)
    assert "portfolio_analyst prepared a plan" in response.text
    assert window.retained_count == 2
    assert [message.role for message in window.messages] == ["user", "assistant"]


def test_telegram_agent_handler_falls_back_when_genai_is_not_configured(monkeypatch) -> None:
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    monkeypatch.setenv("AZURE_OPENAI_ENABLED", "false")

    handler = build_agent_message_handler_if_configured()
    response = handler(
        TelegramInboundMessage(
            chat_id=123,
            text="show my portfolio",
            message_id=1,
        )
    )

    assert isinstance(response, TelegramOutboundMessage)
    assert "agent runtime is not wired yet" in response.text
